---
title: "seurat/cca"
output: 
  html_document: 
    keep_md: yes
date: "2023-06-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(SeuratDisk)
library(Seurat)
library(dplyr)
library(readxl)
library(ggplot2)
library(tibble)
library(future)
library(ggvenn)
library(parallel)
library(randomcoloR)
```



#Try analyse without integration

```{r}
gbm <- readRDS("./../output/seurat_gbm_qc")

# Try analyse without integration
gbm <- NormalizeData(gbm, verbose = FALSE)
gbm <- FindVariableFeatures(gbm, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
gbm <- ScaleData(gbm, verbose = FALSE)
gbm <- RunPCA(gbm, npcs = 30, verbose = FALSE)
gbm <- RunUMAP(gbm, reduction = "pca", dims = 1:30, verbose = FALSE)
# gbm <- RunTSNE(gbm,reduction = "pca", dims = 1:30, verbose = FALSE)
# gbm <- FindNeighbors(gbm, reduction = "pca", dims = 1:30, verbose = FALSE)
# gbm <- FindClusters(gbm, resolution =0.4, verbose = FALSE)
```




```{r}
p0 <- DimPlot(gbm, reduction = "umap", label = TRUE, group.by = "runs")
# p0 <- p0 + labs(subtitle = "control + radiated; no integration")
p0 <- p0 + labs(subtitle = "control + radiated; 2 runs ; no integration")
p0
```
```{r}
p0 <- DimPlot(gbm, reduction = "umap", label = TRUE, group.by = "batch", repel = TRUE)
# p0 <- p0 + labs(subtitle = "control + radiated; no integration")
p0 <- p0 + labs(subtitle = "control + radiated; 2 runs ; no integration")
p0
```
```{r}
p0 <- DimPlot(gbm, reduction = "umap", label = TRUE, group.by = "donor_id", repel = TRUE)
# p0 <- p0 + labs(subtitle = "control + radiated; no integration")
p0 <- p0 + labs(subtitle = "control + radiated; 2 runs ; no integration")
p0
```

```{r}
Idents(gbm) <- "donor_id"
sub <- subset(gbm, idents = c("E31N", "E24N", "E26N"))
```


```{r}
p0 <- DimPlot(sub, reduction = "umap", group.by = "donor_id", split.by = "batch", ncol = 2)
p0
```



```{r}
Idents(gbm) <- "runs"
gbm.run2 <- subset(gbm, idents = "run2")
gbm.run2 <- NormalizeData(gbm.run2, verbose = FALSE)
gbm.run2 <- FindVariableFeatures(gbm.run2, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
gbm.run2 <- ScaleData(gbm.run2, verbose = FALSE)
gbm.run2 <- RunPCA(gbm.run2, npcs = 30, verbose = FALSE)
gbm.run2 <- RunUMAP(gbm.run2, reduction = "pca", dims = 1:30, verbose = FALSE)
```

```{r}
install.packages("sctransform")
```




```{r}
p0 <- DimPlot(gbm.run2, reduction = "umap", label = TRUE, group.by = "batch", repel = TRUE)
p0 <- p0 + labs(subtitle = "control + radiated; run2 ; no integration")
p0
```


```{r}
p0 <- DimPlot(gbm.run2, reduction = "umap", label = TRUE, group.by = "donor_id", repel = TRUE)
p0 <- p0 + labs(subtitle = "control + radiated; run2 ; no integration")
p0
```
```{r}
Idents(gbm.run2) <- "donor_id"
gbm.run2.E37N <- subset(gbm.run2, idents = "E37N")
gbm.run2.E37N
```

```{r}
gbm <- AddMetaData(gbm, metadata = metamodule.4.new50.onlydiverge["consensus"], col.name = "new50_onlydiverge")
# gbm <- AddMetaData(gbm,metadata = metamodule.4.new50.byconsistency["consensus"],col.name = "new50_byconsistency")
# gbm <- AddMetaData(gbm,metadata = mes.imm["consensus"],col.name = "mes_imm")
```

```{r}
p0 <- DimPlot(gbm, reduction = "umap", group.by = "new50_byconsistency")
p0
```


```{r}
p0 <- DimPlot(gbm, reduction = "umap", group.by = "new50_onlydiverge")
p0
```



```{r}
p0 <- DimPlot(gbm.run2.E37N, reduction = "umap", group.by = "new50_onlydiverge", split.by = "radiation", ncol = 2)
p0
```








#integrate on ...
```{r}
# Load data
gbm <- readRDS("./../output/seurat_gbm_qc")
```


```{r}
integration.method <- "donor_id"
gbm.list <- SplitObject(gbm, split.by = integration.method)
rm(gbm)
```


```{r}
# normalize and identify variable features for each dataset independently
gbm.list <- mclapply(X = gbm.list, mc.cores = (parallel::detectCores() - 2), FUN = function(x) {
  x <- NormalizeData(x, verbose = FALSE)
  x <- FindVariableFeatures(x, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
  # VariableFeatures(x) <- union(VariableFeatures(x), unlist(signatures))
})
```


```{r}
# select features that are repeatedly variable across datasets for integration
features <- SelectIntegrationFeatures(object.list = gbm.list, verbose = FALSE, nfeatures = 2000)

# #Add sub-type into variable
# for (i in 1:length(gbm.list)) {
#   VariableFeatures(gbm.list[[i]]) <- union(VariableFeatures(gbm.list[[i]]), signatures)
# }

# Add subtype to features
signatures <- read.csv(file = paste0("./../output/signature_subtype_", sig, ".csv"))
signatures <- unlist(signatures)
names(signatures) <- NULL
signatures

features <- union(
  features,
  intersect(signatures, rownames(gbm@assays$RNA@meta.features))
)


# plan("cluster", workers = 1)
# plan("sequential")
gc()
```


```{r}
plan("cluster", workers = 4)
gbm.anchor <- FindIntegrationAnchors(object.list = gbm.list, anchor.features = features, verbose = TRUE)

gc()

# this command creates an 'integrated' data assay

gbm.combined.integrated <- IntegrateData(anchorset = gbm.anchor, verbose = TRUE)


rm(gbm.list)
gc()
```

```{r}
saveRDS(gbm.combined.integrated, file = paste0("./../output/seurat_gbm_integrated_", integration.method, "_plus_subtype"), compress = TRUE)
```



#Post integral analysis 
```{r}
integration.method <- "donor_id"
gbm.combined.integrated <- readRDS(file = paste0("./../output/seurat_gbm_integrated_", integration.method, "_plus_subtype"))
```

```{r}
metamodule.4.new50.onlydiverge <- read.csv("./../output/consensus_all_4metamodules_new_50_only_diverge.csv", row.names = 1)
mes.imm <- read.csv("./../output/consensus_all_MESImm_marker_based.csv")
rownames(mes.imm) <- mes.imm$X
```

```{r}
gbm.combined.integrated <- AddMetaData(gbm.combined.integrated, metadata = metamodule.4.new50.onlydiverge["consensus"], col.name = "new50_onlydiverge")
gbm.combined.integrated <- AddMetaData(gbm.combined.integrated, metadata = mes.imm["consensus"], col.name = "mes_imm")
```

```{r}
set.seed(1)
# Run the standard workflow for visualization and clustering
DefaultAssay(gbm.combined.integrated) <- "integrated"
gbm.combined.integrated <- ScaleData(gbm.combined.integrated, verbose = FALSE)
gbm.combined.integrated <- RunPCA(gbm.combined.integrated, npcs = 30, verbose = FALSE)
gbm.combined.integrated <- RunUMAP(gbm.combined.integrated, reduction = "pca", dims = 1:30)

# gbm.combined.integrated <- FindNeighbors(gbm.combined.integrated, reduction = "pca", dims = 1:30)
# gbm.combined.integrated <- FindClusters(gbm.combined.integrated, resolution = 0.13)
```

```{r}
set.seed(1)
group_by <- "batch"
palette <- distinctColorPalette(length(unique(gbm.combined.integrated[[]][, group_by])))
p <- DimPlot(gbm.combined.integrated, group.by = group_by, cols = palette) +
  theme(
    strip.text.x = element_text(size = 4, face = "bold"),
    axis.text = element_blank(),
    legend.text = element_text(size = 4, face = "bold")
  )
p
```
```{r}
set.seed(1)
group_by <- "donor_run"
palette <- distinctColorPalette(length(unique(gbm.combined.integrated[[]][, group_by])))
p <- DimPlot(gbm.combined.integrated, group.by = group_by, cols = palette) +
  theme(
    strip.text.x = element_text(size = 4, face = "bold"),
    axis.text = element_blank(),
    legend.text = element_text(size = 4, face = "bold")
  )
LabelClusters(p, id = group_by, fontface = "bold", color = "red", size = 2, repel = TRUE)
```
```{r}
set.seed(1)
group_by <- "radiation"
palette <- distinctColorPalette(length(unique(gbm.combined.integrated[[]][, group_by])))
p <- DimPlot(gbm.combined.integrated, group.by = group_by, cols = palette) +
  theme(
    strip.text.x = element_text(size = 4, face = "bold"),
    axis.text = element_blank(),
    legend.text = element_text(size = 4, face = "bold")
  )
p
```

```{r}
set.seed(1000)
group_by <- "split"
palette <- distinctColorPalette(length(unique(gbm.combined.integrated[[]][, group_by])))
p <- DimPlot(gbm.combined.integrated, group.by = group_by, cols = palette) +
  theme(
    strip.text.x = element_text(size = 4, face = "bold"),
    axis.text = element_blank(),
    legend.text = element_text(size = 4, face = "bold")
  )
LabelClusters(p, id = group_by, fontface = "bold", color = "darkred", size = 1.5, repel = TRUE)
```


```{r}
set.seed(1)
group_by <- "donor_radiation"
palette <- distinctColorPalette(length(unique(gbm.combined.integrated[[]][, group_by])))
p <- DimPlot(gbm.combined.integrated, group.by = group_by, cols = palette) +
  theme(
    strip.text.x = element_text(size = 4, face = "bold"),
    axis.text = element_blank(),
    legend.text = element_text(size = 4, face = "bold")
  )
LabelClusters(p, id = group_by, fontface = "bold", color = "red", size = 2, repel = TRUE)
```
```{r}
set.seed(1)
group_by <- "radiation"
split_by <- "donor_id"
palette <- distinctColorPalette(length(unique(gbm.combined.integrated[[]][, group_by])))
p <- DimPlot(gbm.combined.integrated, group.by = group_by, cols = alpha(palette, 0.1), split.by = split_by, ncol = 4, pt.size = 0.001) +
  theme(
    strip.text.x = element_text(size = 4, face = "bold"),
    axis.text = element_blank(),
    legend.text = element_text(size = 4, face = "bold")
  )
# LabelClusters(p, id = group_by,  fontface = "bold", color = "red",size = 2, repel = TRUE )
p
```




```{r}
DimPlot(gbm.combined.integrated, group.by = "new50_onlydiverge")
```
```{r}
DimPlot(gbm.combined.integrated, group.by = "new50_onlydiverge", split.by = "radiation")
```
```{r}
DimPlot(gbm.combined.integrated, split.by = "new50_onlydiverge", group.by = "radiation", ncol = 3)
```




```{r}
DimPlot(gbm.combined.integrated, group.by = "new50_onlydiverge", split.by = "split", ncol = 6) +
  theme(
    strip.text.x = element_text(size = 4, face = "bold"),
    axis.text = element_blank(),
    legend.text = element_text(size = 5, face = "bold")
  )
```
```{r}
DimPlot(gbm.combined.integrated, group.by = "mes_imm")
```
```{r}
DimPlot(gbm.combined.integrated, group.by = "mes_imm", split.by = "radiation")
```

```{r}
# Check intersection with each other
signatures <- read.csv("./../output/signature_subtype_new_50.csv")
```


```{r}
x <- list(integrate.var = gbm.combined.integrated@assays$integrated@var.features, NPC = signatures$NPC.new, OPC = signatures$OPC.new, AC = signatures$AC.new, MES = signatures$MES.new)

vein <- ggvenn(x)
vein <- vein + labs(title = "integrate_donor_run")
vein
```



```{r}
signatures.unlist <- unlist(signatures)
names(signatures.unlist) <- NULL
```


```{r}
x <- list(integrate.var = gbm.combined.integrated@assays$integrated@var.features, sig = signatures.unlist)
vein <- ggvenn(x)
vein <- vein + labs(title = "integrate_donor_run")
vein
```

```{r}
intersect.genes <- intersect(gbm.combined.integrated@assays$integrated@var.features, signatures.unlist)
intersect.genes
```



```{r}
gbm.combined.integrated <- RunPCA(gbm.combined.integrated, features = intersect.genes)
```

```{r}
ElbowPlot(gbm.combined.integrated, ndims = 30)
```



```{r}
gbm.combined.integrated <- RunUMAP(gbm.combined.integrated, dims = 1:30)
# gbm.combined.integrated <- RunTSNE(gbm.combined.integrated,dims = 1:10)
```

```{r}
DimPlot(gbm.combined.integrated, group.by = "new50_onlydiverge")
```


```{r}
DimPlot(gbm.combined.integrated, group.by = "new50_onlydiverge", split.by = "donor_radiation", ncol = 6) +
  theme(
    strip.text.x = element_text(size = 6, face = "bold"),
    axis.text = element_blank(),
    legend.text = element_text(size = 5, face = "bold")
  )

# gbm.combined.integrated$donor_radiation <- paste0(gbm.combined.integrated$donor_id,"_",gbm.combined.integrated$radiation)
```

```{r}
DimPlot(gbm.combined.integrated, group.by = "new50_onlydiverge", split.by = "new50_onlydiverge", ncol = 3)
```



```{r}
p <- DoHeatmap(gbm.combined.integrated, features = signatures$NPC.new, group.by = "new50_onlydiverge")
p <- p + labs(title = "NPC.new")
p
```

```{r}
p <- DoHeatmap(gbm.combined.integrated, features = signatures$AC.new, group.by = "new50_onlydiverge")
p <- p + labs(title = "AC.new")
p
```
```{r}
p <- DoHeatmap(gbm.combined.integrated, features = signatures$OPC.new, group.by = "new50_onlydiverge")
p <- p + labs(title = "OPC.new")
p
```

```{r}
p <- DoHeatmap(gbm.combined.integrated, features = signatures$MES.new, group.by = "new50_onlydiverge")
p <- p + labs(title = "MES.new")
p
```



```{r}
signatures.mem <- read_xlsx("./../data/MESImm_original.xlsx", sheet = 3)
signatures.mem
```

```{r}
p <- DoHeatmap(gbm.combined.integrated, features = signatures.mem$MESImm, group.by = "mes_imm")
p <- p + labs(title = "MESImm_gene")
p
```

```{r}
p <- DoHeatmap(gbm.combined.integrated, features = signatures.mem$Non_MESImm, group.by = "mes_imm")
p <- p + labs(title = "Non_MESImm gene")
p
```

