```{r}
library(ggplot2)
library(GGally)
library(dplyr)
library(tidyr)
library(patchwork)
library(tibble)
```


#Combine
```{r}
#Import metadata
gbm.meta <- read.csv("./../output/gbm_meta.csv",row.names = 1)

#import all data 
sc.sorter <- read.csv(paste0("./../output/scsorter_",object,"_",sig,".csv"),row.names = 1)
marker.count <- read.csv(paste0("./../output/markercount_",object,"_",sig,".csv"),row.names = 1)
sc.type <- read.csv(paste0("./../output/scType_",object,"_",sig,".csv"),row.names = 1)

celltype.list <- list(sc.sorter,marker.count,sc.type)
```

```{r}

head(sc.sorter)
head(marker.count)
head(sc.type)

```

```{r}
library(tibble)
celltype.list <- lapply(X=celltype.list, FUN = function(x) {
  x <- rownames_to_column(x,var = "cell_id")
  x <- x[1:2]
})

library(tidyverse)
celltype.df <- celltype.list %>% reduce(inner_join, by='cell_id')

celltype.df
```

```{r}
#set name to be the same
all <- celltype.df


all <- data.frame(lapply(all, function (x) {gsub(c("Unknown"), "unknown",x)}))
all <- data.frame(lapply(all, function (x) {gsub(c("unassigned"), "unknown",x)}))
all <- data.frame(lapply(all, function (x) {gsub(c("unknown"), "unknown",x)}))





#Change 1 column back to row_names
rownames(all) <- all[,1]
all <- all[-1]

head(all)
table(unlist(all))
```






```{r}
#Test varying consesus
all.consensus<- all[,0]
tools.total <- ncol(all)
resolution <- seq(0, 1, by=0.5)
resolution
for (n in resolution) {
  cut.off <- n
  keeps <- c()
  print(n)
  for (i in 1:nrow(all)) {
    if (max(table(unlist(all[i,])))/tools.total >= cut.off) {
      keep <- TRUE
    } else {
      keep <- FALSE
    }
  keeps <- append(keeps,keep)
  }
  all.consensus<- cbind(all.consensus,keeps)
  print("finish")
}

colnames(all.consensus) <- paste0("res_",as.character(resolution))
all.consensus
```






```{r}
resolution.char <- rep(colnames(all.consensus),2)
filter <- c(rep("pass",ncol(all.consensus)),rep("fail",ncol(all.consensus)))
#Counts 
counts <- c()
for (i in 1:ncol(all.consensus)) {
  counts <- c(counts,sum(all.consensus[,i]))
}
counts <- append(counts, ((nrow(all.consensus))-counts))

all.consensus.vary <- data.frame(resolution.char,filter,counts)
all.consensus.vary
```


```{r}
# Stacked + percent
ggplot(all.consensus.vary, aes(x=resolution.char, fill=filter, y=counts)) + geom_bar(position="fill", stat="identity") + 
  theme(
    axis.text.x = element_text(angle = 90)
  )
```

#Try IQV
```{r}
#install.packages('qualvar')
library(qualvar)
```


```{r}
#Calculate frequency for each
for (i in 1:ncol(all)) {
  all[,i] <- as.factor(all[,i])
  levels(all[,i]) <- c(levels(all[,i]), "MESImm", "Non-MESImm ", "unknown" )
} 

all.freq <- data.frame()
i <- 1
while (i  <= nrow(all)) {
  all.freq <- rbind(all.freq, table(unlist(all[i,])))
  i <- i+1
}
#set colname and rowname
colnames(all.freq) <- levels(all[,1]) 
rownames(all.freq)  <- rownames(all)
```


```{r}
all.iqv <- all.freq[,0]

all.iqv$DM <- apply(all.freq, 1, DM)
all.iqv$MDA <- apply(all.freq, 1, MDA)
all.iqv$ADA <- apply(all.freq, 1, ADA)
all.iqv$VA <- apply(all.freq, 1, VA)
all.iqv$HREL <- apply(all.freq, 1, HREL)
all.iqv$B <- apply(all.freq, 1, B)


# 0 mean more consistence; 1 mean zero agreement

all.iqv <- format(round(all.iqv, 3), nsmall = 3)

for (i in 1:ncol(all.iqv)) {
  all.iqv[,i] <- as.numeric(all.iqv[,i])
}


all.iqv
```

```{r}
#Check the range of 
unique(all.iqv[,1])
test <- list()
for (i in 1:ncol(all.iqv)) {
  test <- append(test,list(unique(all.iqv[,i])))
}
test
```



```{r}
library(ggplot2)
library(GGally)
all.iqv %>%
  ggpairs(progress = FALSE) +
  theme_bw()
```

```{r}

#calculate bin width 
library(patchwork)

bin_num <- 10

p1 <- ggplot(all.iqv, aes(x=DM)) + geom_histogram(bins =  bin_num)
p2 <- ggplot(all.iqv, aes(x=MDA)) + geom_histogram(bins =  bin_num)
p3 <- ggplot(all.iqv, aes(x=ADA)) + geom_histogram(bins =  bin_num)
p4 <- ggplot(all.iqv, aes(x=VA)) + geom_histogram(bins =  bin_num)
p5 <- ggplot(all.iqv, aes(x=HREL)) + geom_histogram(bins =  bin_num) 
p6 <- ggplot(all.iqv, aes(x=B)) + geom_histogram(bins =  bin_num)

(p1 + p2 + p3) / (p4 + p5 + p6)
```

```{r}
#color_by resolution
all.iqv.con <- data.frame()
all.iqv.con <- cbind(all.iqv,all.consensus)

p1 <- ggplot(all.iqv.con, aes(x=DM, fill = 1)) + geom_histogram(bins = bin_num)
p1
```


```{r}
#Plot lolipop
all.iqv.freq <- data.frame()
for (i in 1:ncol(all.iqv)){
  all.iqv.freq.each <- data.frame(table(all.iqv[,i]))
  all.iqv.freq.each <- cbind(all.iqv.freq.each, data.frame(method = rep(colnames(all.iqv)[i],nrow(all.iqv.freq.each))))
  all.iqv.freq <- rbind(all.iqv.freq,all.iqv.freq.each)
}

colnames(all.iqv.freq)[1] <- "score"

all.iqv.freq$score <- as.numeric(as.character(all.iqv.freq$score))

all.iqv.freq

#also for log scale
all.iqv.freq <- all.iqv.freq %>% 
  mutate(logFreq = log(Freq))

all.iqv.freq
```
```{r}
ggplot(all.iqv.freq, aes(x=score, y=Freq)) +
#ggplot(all.iqv.freq, aes(x=score, y=logFreq)) +
  geom_point(size=0.2) + 
  geom_segment( aes(x=score, xend=score, y=0, yend=Freq)) + 
  facet_wrap(~ method)
```

```{r}
#ggplot(all.iqv.freq, aes(x=score, y=Freq)) +
ggplot(all.iqv.freq, aes(x=score, y=logFreq)) +
  geom_point(size=0.2) + 
  geom_segment( aes(x=score, xend=score, y=0, yend=logFreq)) + 
  facet_wrap(~ method)
```

#Choose 1 concescus cut off
```{r}
# Stacked + percent
ggplot(all.consensus.vary, aes(x=resolution.char, fill=filter, y=counts)) + geom_bar(position="fill", stat="identity") + 
  theme(
    axis.text.x = element_text(angle = 90)
  )
```

```{r}
#Assign cell_type by mode

vals <- c()

getmode <- function(v) {
   uniqv <- unique(v)
   uniqv[which.max(tabulate(match(v, uniqv)))]
}

for (i in 1:nrow(all)) {
val <- getmode(unlist(all[i,]))
vals <- append(vals,val)
}

# all.consensus.pick <- all.consensus[paste0("res_",as.character(pick.choice))]
all.consensus$consensus <- vals
```




```{r}
all.consensus 
```

```{r}
#Save for future 
#write.csv(all.consensus, "./../output/consensus_all_MESImm.csv", row.names = TRUE)
```

```{r}
#Do sankey
library(ggsankey)
library(ggplot2)

all.sankey <- cbind(all,all.consensus["consensus"])
for (i in 1:ncol(all.sankey)) {
  all.sankey[,i] <- paste0(all.sankey[,i],"_",i)
}

all.sankey

df <- all.sankey %>%
  make_long(colnames(all.sankey))
df
```


```{r}
# Chart 1
pl <- ggplot(df, aes(x = x
                     , next_x = next_x
                     , node = node
                     , next_node = next_node
                     , fill = factor(node)
                     , label = node)
             )
pl <- pl +geom_sankey(flow.alpha = 0.5
                      , node.color = "black"
                      ,show.legend = FALSE)
pl <- pl +geom_sankey_label(size = 2, color = "black", fill= "white")
pl <- pl +  theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl +  theme(axis.title = element_blank()
                  , axis.text.y = element_blank()
                  , axis.ticks = element_blank()  
                  , panel.grid = element_blank()
                  )

#pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = "All")
pl <- pl + labs(fill = 'Nodes')
pl

```
```{r}
#Filter out only on consensus
resolution..colnames <-colnames(all.consensus)

res.keep <- resolution..colnames[2]


all.keep <- cbind(all,all.consensus[c("consensus")])
all.keep <- all.keep[all.consensus[,res.keep] == TRUE,]
all.keep

```
```{r}
#Do sankey
library(ggsankey)
library(ggplot2)
## transform_data

all.keep.sankey <- all.keep
for (i in 1:ncol(all.keep.sankey)) {
  all.keep.sankey[,i] <- paste0(all.keep.sankey[,i],"_",i)
}


df <- all.keep.sankey %>%
  make_long(colnames(all.keep.sankey))
df
```

```{r}
# Chart 1
pl <- ggplot(df, aes(x = x
                     , next_x = next_x
                     , node = node
                     , next_node = next_node
                     , fill = factor(node)
                     , label = node)
             )
pl <- pl +geom_sankey(flow.alpha = 0.5
                      , node.color = "black"
                      ,show.legend = FALSE)
pl <- pl +geom_sankey_label(size = 2, color = "black", fill= "white")
pl <- pl +  theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl +  theme(axis.title = element_blank()
                  , axis.text.y = element_blank()
                  , axis.ticks = element_blank()  
                  , panel.grid = element_blank())
#pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = paste0("All_filterd_",res.keep))
pl <- pl + labs(fill = 'Nodes')
```


```{r}
pl
```



```{r}
# If want the filter version
all.meta.consensus <- merge(gbm.meta,all.consensus,by = "row.names", all = TRUE)
```

```{r}
#visualization
#Utilize old code

each.meta.all <- all.meta.consensus 



each.meta.list <- list()

for (i in radiation){
  donor.group <- i
  each.meta <- subset(each.meta.all,radiation == donor.group)
  
  each.meta <- each.meta %>%
  group_by(donor_id, consensus) %>%
  summarise(count = n()) %>%
  group_by(donor_id) %>%
  mutate(per=count/sum(count)) %>% 
  ungroup()
  
  each.meta <- each.meta %>% 
  cbind(data.frame(radiation = rep(donor.group,length(each.meta$consensus))))
  each.meta.list[[length(each.meta.list) + 1]] <- each.meta
}

each.meta.df <- data_frame()
for (i in 1:length(each.meta.list)) {
  each.meta.df <- rbind(each.meta.df,(each.meta.list[[i]]))
}

each.meta.df
```


```{r}
#Visualisation
ggplot(each.meta.df, aes(x= "", y = per, fill=consensus)) + 
  geom_col() +
  facet_wrap(~  donor_id  + radiation, ncol = 6)+
  ggtitle(" ") +
  coord_polar("y", start=0) +
  theme_void() +
  #geom_text(aes(label = per_round), position = position_stack(vjust = 0.5), size = 1) + 
  labs(title="All donors", subtitle = "consensus")
```
```{r}

#Visualisation
ggplot(each.meta.df, aes(x= "", y = per, fill=consensus)) + 
  geom_col() +
  facet_wrap(~ radiation + donor_id, ncol = 13)+
  ggtitle(" ") +
  coord_polar("y", start=0) +
  theme_void() +
  #geom_text(aes(label = per_round), position = position_stack(vjust = 0.5), size = 1) + 
  labs(title="All donors", subtitle = paste0("consensus_no_filtered; num_tools = ",as.character(ncol(all))))
```





