
```{r}
#library(renv)
#renv::init()

```

```{r}
library(dplyr)
library(here)
library(tidyr)
library(tibble)
library(easyCODA)
#library(zCompositions) it will interfere with dplyr select function
library(topsis)
library(ggplot2)
```

```{r}
select
```

```{r}
#Set working directory
setwd(here())
source("script/function.R")
```
```{r}

# Parameter
# cell input to be analyse

object <- "all"

sigs <- c( "4metamodules_new_50_mes","2metamodules_NPC_OPC", "3metamodules_new_50", "4metamodules_new_50","npcopc_ac_mes","npcopc_acmes")



# For reference based
merges <- c("4_merge_metamodules_mes","2_merge_metamodules",  "4_merge_metamodules_3celltypes","4_merge_metamodules","npcopc_ac_mes","npcopc_acmes")


unknowns <- c("","_no_unknown")


run_eachs <- c(TRUE,FALSE)
runs <- c("each","whole")


possible_cellstate <- c("AClike","NPClike","OPClike","MESlike","unknown","tie")

```
```{r}
#set unknown 
unknown <- unknowns[1]

#set whole vs each
run_each <- run_eachs[1]

#3 celltype

pick <- 4

sig <- sigs[pick]
merge <- merges[pick]


run_each <- run_eachs[1]
if (run_each) {
  run <- runs[1]
} else {
  run <- runs[2]
}



```

```{r}
gbm.meta <- read.csv("output/gbm_meta.csv",row.names = 1)
gbm.meta
```

```{r}
# import all data
# marker.based
sc.type <- read.csv(paste0("output/tools/scType_", object, "_", sig,"_",run, ".csv"), row.names = 1)
sc.type <- sc.type[,paste0("scType",unknown) ,drop = FALSE]

scina <- read.csv(paste0("output/tools/SCINA_", object, "_", sig,"_",run, ".csv"), row.names = 1)
scina <- scina[,paste0("SCINA",unknown) ,drop = FALSE]

scina
# add full option
sc.sorter <- read.csv(paste0("output/tools/scsorter_", object, "_", sig, "_",run,".csv"), row.names = "cell_id")
sc.sorter$scSorter_no_unknown <- sc.sorter$scSorter
sc.sorter <- sc.sorter[,paste0("scSorter",unknown) ,drop = FALSE]

```


```{r}
#unknown <- unknowns[1]
# ref-based
clustify.r <- read.csv(paste0("output/clustifyr_", object, "_", merge, "_",run,".csv"), row.names = 1)
#clustify.r <- clustify.r[,paste0("clustifyr_ref",unknown) ,drop = FALSE]
clustify.r <- clustify.r[,paste0("clustifyr_ref") ,drop = FALSE]

scid <- read.csv(paste0("output/scID_", object, "_", merge,"_allassigned","_",run,".csv"), row.names = 1)
scid$scid_no_unknown <- scid$scID_no_unknown #the current ScID is edited is not working
#scid$scID_no_unknown <- scid$scID
scid <- scid[,paste0("scID",unknown) ,drop = FALSE]

```


```{r}
#Add Full option
sc.pred <- read.csv(paste0("output/scpred_", object, "_", merge, "_",run, ".csv"), row.names = 1)
sc.pred <- sc.pred[,2:1]
colnames(sc.pred) <- c("scPred",paste0("scPred",unknowns[2]))
sc.pred <- sc.pred[,paste0("scPred",unknown) ,drop = FALSE]

single.r <- read.csv(paste0("output/singleR_", object, "_", merge, "_",run, ".csv"), row.names = 1)
single.r <- single.r[,2:1]
colnames(single.r) <- c("singleR",paste0("singleR",unknowns[2]))
single.r[is.na(single.r$singleR),"singleR"] <- "unknown"
single.r <- single.r[,paste0("singleR",unknown) ,drop = FALSE]

scibet <- read.csv(paste0("output/scibet_", object, "_", merge,  "_",run,".csv"), row.names = 1)
scibet$scibet_no_unknown <- scibet$scibet #no unknown by default
scibet <- scibet[,paste0("scibet",unknown) ,drop = FALSE]

chetah <- read.csv(paste0("output/CHETAH_", object, "_", merge, "_",run, ".csv"), row.names = 1)
chetah$CHETAH_no_unknown <- chetah$CHETAH
chetah <- chetah[,paste0("CHETAH",unknown) ,drop = FALSE]

scmap_cluster <- read.csv(paste0("output/scmap_cluster_", object, "_", merge,  "_",run,".csv"), row.names = 1)
scmap_cluster$scmap_cluster_no_unknown <- scmap_cluster$scmap_cluster_adjust #cannot tweak to have no unknown
scmap_cluster <- scmap_cluster[,paste0("scmap_cluster",unknown) ,drop = FALSE]

scmap_cell <- read.csv(paste0("output/scmap_cell_", object, "_", merge,  "_",run,".csv"), row.names = 1)
scmap_cell$scmap_cell_no_unknown <- scmap_cell$scmap_cell_adjust #cannot tweak to have no unknown
scmap_cell <- scmap_cell[,paste0("scmap_cell",unknown) ,drop = FALSE]
```

```{r}
sc.type;scina; clustify.r;scid;sc.sorter;sc.pred;scibet;chetah;single.r;scmap_cluster;scmap_cluster
```


```{r}
anno_cellstate <- bind_cols(sc.type, scina, clustify.r,scid)

#full option
anno_cellstate <- bind_cols(sc.type, scina, sc.sorter,clustify.r,scid,sc.pred,scibet,chetah,single.r,scmap_cluster,scmap_cell)

#colnames(anno_cellstate) <- paste(colnames(anno_cellstate), sig, sep = "_")
anno_cellstate[] <- lapply(anno_cellstate, function(x) gsub("NPC_OPC$", "NPC_OPClike", x))
anno_cellstate[] <- lapply(anno_cellstate, function(x) gsub("AC$", "AClike", x))
anno_cellstate[] <- lapply(anno_cellstate, function(x) gsub("MES$", "MESlike", x))
anno_cellstate[] <- lapply(anno_cellstate, function(x) gsub("AC_MES$", "AC_MESlike", x))
anno_cellstate[] <- lapply(anno_cellstate, function(x) gsub("\\.new$", "like", x))
anno_cellstate[] <- lapply(anno_cellstate, function(x) gsub("Unknown", "unknown", x))
anno_cellstate[] <- lapply(anno_cellstate, function(x) gsub("unassigned", "unknown", x))

```
```{r}
anno_cellstate
```

```{r}
anno_cellstate[grepl("_r",rownames(anno_cellstate)) == TRUE,]
```
```{r}
anno_cellstate
```


```{r}
anno_cellstate_meta <- merge(gbm.meta[,c("donor_radiation","donor_id","radiation")],anno_cellstate,by = "row.names", all = FALSE)
anno_cellstate_meta$donor_radiation <- as.factor(anno_cellstate_meta$donor_radiation)


rownames(anno_cellstate_meta) <- anno_cellstate_meta$Row.names
anno_cellstate_meta <- anno_cellstate_meta[,-1]

anno_cellstate_meta
```

```{r}
# Do sankey
library(ggsankey)
library(ggplot2)
library(patchwork)
library(ggtext)


my_colors <- c("red", "green", "blue", "gray", "purple", "orange")
plots_list <- list()

for (i in levels(anno_cellstate_meta$donor_radiation)) {
  anno_cellstate_meta_each <- anno_cellstate_meta[anno_cellstate_meta$donor_radiation == i,]
  anno_cellstate_meta_each <- anno_cellstate_meta_each %>% dplyr::select(-1:-3)
  all.sankey <- anno_cellstate_meta_each
  colnames(all.sankey) <- gsub("_no_unknown","",colnames(all.sankey))
  df <- all.sankey %>%
    make_long(colnames(all.sankey))

  # Chart 1
  pl <- ggplot(df, aes(
    x = x,
    next_x = next_x,
    node = node,
    next_node = next_node,
    fill = factor(node),
    label = node
  ))
  pl <- pl + geom_sankey(
    flow.alpha = 0.5,
    node.color = "black",
    show.legend = FALSE
  )
  #pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
  pl <- pl + theme_bw()
  pl <- pl + theme(legend.position = "none")
  pl <- pl + theme(
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.text.x = element_blank(),
    panel.grid = element_blank()
  )

  pl <- pl + labs(subtitle = paste(i,"; ",
                                   round(nrow(anno_cellstate_meta_each)*100/nrow(anno_cellstate_meta),digits = 2),"%",
                                   sep = ""))
  pl <- pl + labs(fill = "Nodes")
  pl <- pl + scale_fill_manual(values = my_colors)
  plots_list[[i]] <- pl
}

combined_plot <- wrap_plots(plots_list, ncol = 6)


# Assuming 'my_colors' is your color vector and 'df' is your data frame
# Map colors to factor levels
color_mapping <- setNames(my_colors, levels(factor(df$node)))

# Construct the caption string dynamically
caption_text <- paste(sapply(names(color_mapping), function(node) {
  sprintf("<span style='color: %s;'>%s</span>", color_mapping[node], node)
}), collapse = " ")

combined_plot + plot_annotation(
    title = paste0(paste(setdiff(levels(factor(df$node)),"unknown"),collapse = ", ") ," cell states","; ",unknown,"; ",run),
    subtitle = caption_text,
    caption = paste(colnames(anno_cellstate),collapse = "; "),
    theme = theme(plot.subtitle = element_markdown())
)
```



#Choose tools: start from 10/ Jan/ 24
```{r}
# anno_cellstate_meta_control <- anno_cellstate_meta[,-1] %>%
#   filter(radiation == radiation_chosen) %>%
#   dplyr::select(!c(radiation))
# unique_tool <- unique(
#   unlist(
#   anno_cellstate_meta_control[,!colnames(anno_cellstate_meta_control) %in% "donor_id"]
#   )
#   )
# unique_donor_id <- unique(anno_cellstate_meta_control$donor_id)
# 
# unique_tool_donor_id <- length(unique_tool)*length(unique_donor_id)
# 
# 
# 
# count_all_list <- list()
# count_all <- data.frame(matrix(nrow = unique_tool_donor_id, ncol = 0))
# prop_all <- data.frame(matrix(nrow = unique_tool_donor_id, ncol = 0))
# for (i in 2:ncol(anno_cellstate_meta_control)) {
#   anno_cellstate_meta_eachtool <- anno_cellstate_meta_control[,c(1,i)] 
#   # anno_cellstate_meta_eachtool <- anno_cellstate_meta_control[,c("donor_id","scSorter")] 
#   
#   # anno_cellstate_meta_eachtool[,2] <- factor(anno_cellstate_meta_eachtool[,2],levels = possible_cellstate[1:5]) 
#   anno_cellstate_meta_eachtool[,2] <- factor(anno_cellstate_meta_eachtool[,2],levels = unique_tool) 
# 
#   count_tool_alldonor <- data.frame()
#   prop_tool_alldonor <- data.frame()
#   for (q in unique(anno_cellstate_meta_eachtool$donor_id)) {
#     anno_cellstate_meta_eachtool_eachdonor <- anno_cellstate_meta_eachtool[anno_cellstate_meta_eachtool$donor_id == q,]
#     count_tool <- as.data.frame(table(anno_cellstate_meta_eachtool_eachdonor[,2]))
#     #count_tool[,2] <- count_tool[,2]/nrow(anno_cellstate_meta_eachtool_eachdonor)
#     
#     
#     tool_name <- colnames(anno_cellstate_meta_eachtool_eachdonor)[2]
#     colnames(count_tool) <- c("cellstate",tool_name)
#     count_tool$donor_id <- rep(q,times = nrow(count_tool))
#     count_tool_alldonor <- rbind(count_tool_alldonor,count_tool)
#     count_tool_alldonor <- count_tool_alldonor %>% arrange(donor_id,cellstate)
#     
#     prop_tool <- count_tool
#     prop_tool[,2] <- prop_tool[,2]/nrow(anno_cellstate_meta_eachtool_eachdonor)
#     prop_tool_alldonor <- rbind(prop_tool_alldonor,prop_tool)
#     prop_tool_alldonor <- prop_tool_alldonor %>% arrange(donor_id,cellstate)
#     
#     count_tool_alldonor_wide <- spread(count_tool_alldonor, donor_id, tool_name)
#     count_tool_alldonor_wide <- column_to_rownames(count_tool_alldonor_wide,var = "cellstate")
#     count_tool_alldonor_wide <- data.frame(t(count_tool_alldonor_wide))
#     count_all_list[[tool_name]] <- count_tool_alldonor_wide
#     
#     
#   }
#   count_all <- cbind(count_all,count_tool_alldonor[,2,drop = FALSE])
#   prop_all <- cbind(prop_all,prop_tool_alldonor[,2,drop = FALSE])
# }
# 
# count_all <- cbind(count_tool_alldonor[,c(1,3)],count_all)
# prop_all <- cbind(prop_tool_alldonor[,c(1,3)],prop_all)
```

```{r}
anno_cellstate_meta_control <- anno_cellstate_meta %>%
  dplyr::select(!c(donor_id,radiation))
unique_tool <- unique(
  unlist(
  anno_cellstate_meta_control[,!colnames(anno_cellstate_meta_control) %in% "donor_radiation"]
  )
  )
unique_donor_radiation <- unique(anno_cellstate_meta_control$donor_radiation)

unique_tool_donor_radiation <- length(unique_tool)*length(unique_donor_radiation)

unique_tool

count_all_list <- list()
count_all <- data.frame(matrix(nrow = unique_tool_donor_radiation, ncol = 0))
prop_all <- data.frame(matrix(nrow = unique_tool_donor_radiation, ncol = 0))
for (i in 2:ncol(anno_cellstate_meta_control)) {
  anno_cellstate_meta_eachtool <- anno_cellstate_meta_control[,c(1,i)] 
  # anno_cellstate_meta_eachtool <- anno_cellstate_meta_control[,c("donor_radiation","scSorter")] 
  
  # anno_cellstate_meta_eachtool[,2] <- factor(anno_cellstate_meta_eachtool[,2],levels = possible_cellstate[1:5]) 
  anno_cellstate_meta_eachtool[,2] <- factor(anno_cellstate_meta_eachtool[,2],levels = unique_tool) 

  count_tool_alldonor <- data.frame()
  prop_tool_alldonor <- data.frame()
  for (q in unique(anno_cellstate_meta_eachtool$donor_radiation)) {
    anno_cellstate_meta_eachtool_eachdonor <- anno_cellstate_meta_eachtool[anno_cellstate_meta_eachtool$donor_radiation == q,]
    count_tool <- as.data.frame(table(anno_cellstate_meta_eachtool_eachdonor[,2]))
    #count_tool[,2] <- count_tool[,2]/nrow(anno_cellstate_meta_eachtool_eachdonor)
    
    
    tool_name <- colnames(anno_cellstate_meta_eachtool_eachdonor)[2]
    colnames(count_tool) <- c("cellstate",tool_name)
    count_tool$donor_radiation <- rep(q,times = nrow(count_tool))
    count_tool_alldonor <- rbind(count_tool_alldonor,count_tool)
    count_tool_alldonor <- count_tool_alldonor %>% arrange(donor_radiation,cellstate)
    
    prop_tool <- count_tool
    prop_tool[,2] <- prop_tool[,2]/nrow(anno_cellstate_meta_eachtool_eachdonor)
    prop_tool_alldonor <- rbind(prop_tool_alldonor,prop_tool)
    prop_tool_alldonor <- prop_tool_alldonor %>% arrange(donor_radiation,cellstate)
    
    count_tool_alldonor_wide <- spread(count_tool_alldonor, donor_radiation, tool_name)
    count_tool_alldonor_wide <- column_to_rownames(count_tool_alldonor_wide,var = "cellstate")
    count_tool_alldonor_wide <- data.frame(t(count_tool_alldonor_wide))
    count_all_list[[tool_name]] <- count_tool_alldonor_wide
    
    
  }
  count_all <- cbind(count_all,count_tool_alldonor[,2,drop = FALSE])
  prop_all <- cbind(prop_all,prop_tool_alldonor[,2,drop = FALSE])
}

count_all <- cbind(count_tool_alldonor[,c(1,3)],count_all)
prop_all <- cbind(prop_tool_alldonor[,c(1,3)],prop_all)

count_all
prop_all
```





```{r}
library(tibble)
#exclude unknown

count_all_nounknown_list <- lapply(count_all_list,function(x){
x <- x %>% 
  rownames_to_column(var = "rowname") %>% 
  dplyr::select(-unknown) %>%
  rowwise() %>%
  filter(!all(c_across(-rowname) == 0)) %>%
  ungroup()


# Convert the rowname column back to row names
x <- as.data.frame(x)
rownames(x) <- x$rowname
x <- x %>% dplyr::select(-rowname)


})

prop_all_nounknown_list <- lapply(count_all_nounknown_list,function(x){
  x <- x/rowSums(x) 
})

count_all_nounknown_list
prop_all_nounknown_list
```
```{r}
zero_cellstate <- lapply(count_all_nounknown_list, function(x){
  logic <- sum(!(rowSums(x > 0) >= 2)) > nrow(x)*0.1
  return(logic)
})

zero_cellstate
```




```{r}
#unknown proportion

prop_all_unknown_list <- lapply(count_all_list,function(x){
  (x$unknown)/rowSums(x)
})
prop_all_unknown_df <- as.data.frame(prop_all_unknown_list)


prop_all_unknown_mean <- apply(prop_all_unknown_df,2,mean)
prop_all_unknown_median <- apply(prop_all_unknown_df,2,median)

prop_all_unknown_pooled <- lapply(count_all_list,function(x){
  (sum(x$unknown))/sum(x)
})

```



```{r}

impute_fn <- function(x) {
  lapply(x, function(x){
    total_cell <- sum(x)
  # if (any(x == 0)) {
  #   return(zCompositions::cmultRepl(x,z.warning = 0.99,label = 0,method = "SQ",output = "p-counts",))
  # } else {
  #   return(x)
  #}
   
  ##this method just add 1 to all, could be biased for the donor id with low cell number  
  x <- x+0.0001
    
  # # add pseudocount to each donor_id weight by the cell count
  # 
  # x <- x + (rowSums(x))/total_cell
})
}

count_all_list_imputed <- impute_fn(count_all_list)

count_all_nounknown_list_imputed <- impute_fn(count_all_nounknown_list)
```
```{r}
#convert count_imputed to prop_imputed
count_to_prop_fn <- function(x) {
  lapply(x, function(x) {
  data.frame(t(apply(x,1,function(x) x/sum(x))))
})
}
prop_all_list_imputed <- count_to_prop_fn(count_all_list_imputed)
prop_all_nounknown_list_imputed <- count_to_prop_fn(count_all_nounknown_list_imputed)

prop_all_nounknown_list_imputed
```


```{r}
weight <- TRUE
```

```{r}
#calculate clr
prop_all_list_imputed_clr <- lapply(prop_all_list_imputed, CLR,weight=weight)
prop_all_nounknown_list_imputed_clr <- lapply(prop_all_nounknown_list_imputed, CLR,weight=weight)
```


```{r}
# lapply(prop_all_nounknown_list_imputed, function(x) {
#   print(sum(x == 0) > 0) 
# })
```


```{r}
#calculate log variance
lrv_list <- lapply(prop_all_list_imputed_clr, LR.VAR,weight=weight)
lrv_nounknown_list <- lapply(prop_all_nounknown_list_imputed_clr, LR.VAR,weight=weight)
```


```{r}
#diversify 
#sd-of-cellstate-per-donor_mean_nounknown
sd_mean_nounknown_list <- lapply(prop_all_nounknown_list_imputed, function(x) { # per tool
  x <- apply(x,1,FUN = sd) # sd of cellstate per donor
  x <- mean(x) # mean of sd
  return(x)
})

prop_all_nounknown_list_imputed
sd_mean_nounknown_list
```

```{r}
#choose best tool
lrv_vec <- unlist(lrv_list)
names(lrv_vec) <- names(lrv_list)

lrv_nounknown_vec <- unlist(lrv_nounknown_list)
names(lrv_nounknown_vec) <- names(lrv_nounknown_list)

sd_mean_nounknown_vec <- unlist(sd_mean_nounknown_list)
names(sd_mean_nounknown_vec) <- names(sd_mean_nounknown_list)

tools_matric <- data.frame(lrv = lrv_vec, 
                           lrv_nounknown = lrv_nounknown_vec,
                           sd_mean_nounknown = sd_mean_nounknown_vec,
                           prop_known_mean = (1-prop_all_unknown_mean),
                           prop_known_median = (1-prop_all_unknown_median),
                           prop_known_pooled = (1-unlist(prop_all_unknown_pooled)))


tools_matric %>% arrange(lrv_nounknown)
```

```{r}
#choose best tool
lrv_vec <- unlist(lrv_list)
names(lrv_vec) <- names(lrv_list)

lrv_nounknown_vec <- unlist(lrv_nounknown_list)
names(lrv_nounknown_vec) <- names(lrv_nounknown_list)

sd_mean_nounknown_vec <- unlist(sd_mean_nounknown_list)
names(sd_mean_nounknown_vec) <- names(sd_mean_nounknown_list)

tools_matric <- data.frame(lrv = lrv_vec, 
                           lrv_nounknown = lrv_nounknown_vec,
                           sd_mean_nounknown = sd_mean_nounknown_vec,
                           prop_known_mean = (1-prop_all_unknown_mean),
                           prop_known_median = (1-prop_all_unknown_median),
                           prop_known_pooled = (1-unlist(prop_all_unknown_pooled)))

tools_matric %>% arrange(desc(lrv_nounknown))
```




```{r}
library(MCDA)
score_name <- colnames(tools_matric)
score_name
```


```{r}
weights <- setNames(c(1,1,1,1,0.5,0.5), colnames(tools_matric))
#pick <- c(2,5,6)
pick <- c(2,3)

# weights <- setNames(c(1,1,1,1,1,10), colnames(tools_matric))
# pick <- c(6)
impacts <- c("+","+","-","+","+","+") # For topsis


```


```{r}
#Topsis
tools_topsis_score <- topsis(decision = as.matrix(tools_matric[,score_name[pick]]), weights = weights[pick], impacts = impacts[pick])

tools_topsis_score$alt.row <- rownames(tools_matric)

colnames(tools_topsis_score)[1] <- "tool"

tools_topsis_score_metric <- merge(tools_topsis_score,rownames_to_column(tools_matric,var = "tool"),by = "tool")

tools_topsis_score_metric <- tools_topsis_score_metric %>% arrange(rank)

tools_topsis_score_metric

topsis <- column_to_rownames(tools_topsis_score,var = "tool")
colnames(topsis)[1] <- "topsis"
topsis <- topsis[,-2,drop = FALSE]
```

```{r}
# MCMD: weightedSum 
normalizationtypes <- rep("rescaling",times = ncol(tools_matric))
names(normalizationtypes) <- score_name

tools_matric_norm <- normalizePerformanceTable(
  tools_matric, normalizationTypes = normalizationtypes,
  criteriaIDs = score_name)

weightedSum <- data.frame(weightedSum = weightedSum(tools_matric_norm,
            criteriaWeights = weights[pick],
            criteriaIDs = score_name[pick]))


weightedSum
```



```{r}
# "waspasR" 
library("waspasR")
# tools_matric <- tools_matric %>% dplyr::select(-unknown_mean_weighted_revert)
# tools_matric$unknown_mean_weighted_revert <- 1 -tools_matric$unknown_mean_weighted

flags_input <- ifelse(impacts == "+", "B", "C")

waspas_df <- rbind(t(data.frame(F = flags_input[pick],
           W = weights[pick]/sum(weights[pick]))),
           C = colnames(tools_matric)[pick],
      tools_matric[pick])

waspas_df <- as.tibble(rownames_to_column(waspas_df,var = "tool"))

waspas_raw <- waspasR_edited(waspas_df,lambda = 0.5)
waspas_raw
waspas <- column_to_rownames(waspas_raw,var = "Alternative") 
waspas <- waspas[!rownames(waspas)%in% c("W","F"),c("WSM_Rank","WPM_Rank","WASPAS_Rank")] 
waspas
```
```{r}
# #Manual weight sum
# tools_matric[pick]
```

```{r}
topsis
weightedSum
waspas
```


```{r}
metric <- cbind(topsis,weightedSum,waspas,tools_matric)

metric_names <- colnames(metric)

metric_names
chosen_metric  <- metric_names[3]


chosen_metric
```


```{r}
metric <- metric[order(metric[,chosen_metric],decreasing = TRUE),]


metric$rank <- 1:nrow(metric)

# pick and round chosen score 
metric$score <- metric[,chosen_metric,drop = TRUE]
metric$score <- round(metric$score, digits = 2)

metric
```



```{r}
anno_cellstate_meta_control_sortcol <- 
  cbind(anno_cellstate_meta_control[,1,drop = FALSE],
        anno_cellstate_meta_control[,rownames(metric)])
donor_radiation_bysize <- names(sort(table(anno_cellstate_meta_control_sortcol$donor_radiation),decreasing = TRUE))

anno_cellstate_meta_control_sortcol$donor_radiation <- factor(anno_cellstate_meta_control_sortcol$donor_radiation,levels = donor_radiation_bysize)

anno_cellstate_meta_control_sortcol
```


```{r}
cellstate_colors <- c(
  "OPClike" = "#1f77b4",  # Replace 'cellstate1' with actual cellstate names
  "unknown" = "grey",
  "NPClike" = "#2ca02c",
  "AClike" = "#d62728",
  "MESlike" = "#9467bd"
  # Add more colors as needed for each cellstate
)

tool <- "tool"
proportion <- "proportion"

gathercols <- colnames(prop_all)[!colnames(prop_all) %in% c("cellstate","donor_radiation")]
prop_all_long <- gather(prop_all, tool, proportion, gathercols)
prop_all_long$tool <- factor(prop_all_long$tool,levels = rownames(metric))
prop_all_long$donor_radiation <- factor(prop_all_long$donor_radiation,level = donor_radiation_bysize)
prop_all_long$cellstate <- factor(prop_all_long$cellstate, levels = c("MESlike" ,"OPClike","AClike" , "NPClike", "unknown" ))
plot.prop <- ggplot(prop_all_long, aes(fill=cellstate, y=proportion, x=donor_radiation)) + 
    geom_bar(position="fill", stat="identity") +
  facet_wrap(~tool) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size = 3)) +
  labs(title = "Cellstate annotaion",
       subtitle = paste0("analysed group: ","both"," ; ",run),
       caption = paste0(
                         "metric = ",chosen_metric,"\n",
                         "criteria = ",paste(score_name[pick],collapse = ": "),";  ",
                         "weight = ",paste(weights[pick],collapse = ":"))) +
  scale_fill_manual(values = cellstate_colors)
  


count <- "count"
gathercols <- colnames(count_all)[!colnames(count_all) %in% c("cellstate","donor_radiation")]
count_all_long <- gather(count_all, tool, count, gathercols)
count_all_long$tool <- factor(count_all_long$tool,levels = rownames(metric))
count_all_long$donor_radiation <- factor(count_all_long$donor_radiation,level = donor_radiation_bysize)
count_all_long$cellstate <- factor(count_all_long$cellstate, levels = c("MESlike" ,"OPClike","AClike" , "NPClike", "unknown" ))
plot.count <- ggplot(count_all_long, aes(fill=cellstate, y=count, x=donor_radiation)) + 
    geom_bar(position="stack", stat="identity") +
  facet_wrap(~tool) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size = 3)) +
  labs(title = "Cellstate annotaion",
       subtitle = paste0("analysed group: ","both"," ; ",run),
       caption = paste0(
                         "metric = ",chosen_metric,"\n",
                         "criteria = ",paste(score_name[pick],collapse = ": "),";  ",
                         "weight = ",paste(weights[pick],collapse = ":"))) +
  scale_fill_manual(values = cellstate_colors)


count <- "count"
count_all_nounknown <- count_all %>% 
  filter(!cellstate == "unknown")
gathercols <- colnames(count_all_nounknown)[!colnames(count_all_nounknown) %in% c("cellstate","donor_radiation")]
count_all_nounknown_long <- gather(count_all_nounknown, tool, count, gathercols)
count_all_nounknown_long$tool <- factor(count_all_nounknown_long$tool,levels = rownames(metric))
count_all_nounknown_long$donor_radiation <- factor(count_all_nounknown_long$donor_radiation,level = donor_radiation_bysize)
count_all_nounknown_long$cellstate <- factor(count_all_nounknown_long$cellstate, levels = c("MESlike" ,"OPClike","AClike" , "NPClike", "unknown" ))
plot.count.nounknown <- ggplot(count_all_nounknown_long, aes(fill=cellstate, y=count, x=donor_radiation)) + 
    geom_bar(position="stack", stat="identity") +
  facet_wrap(~tool) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size = 3)) +
  labs(title = "Cellstate annotaion",
       subtitle = paste0("analysed group: ","both"," ; ",run),
       caption = paste0(
                         "metric = ",chosen_metric,"\n",
                         "criteria = ",paste(score_name[pick],collapse = ": "),";  ",
                         "weight = ",paste(weights[pick],collapse = ":"))) + 
  scale_fill_manual(values = cellstate_colors)



prop_all_nounknown <- count_all_nounknown %>%
  group_by(donor_radiation) %>%
  mutate(across(.cols = setdiff(names(.), c("cellstate", "donor_radiation")),
                .fns = ~ .x / sum(.x))) %>%
  ungroup()

tool <- "tool"
proportion <- "proportion"
gathercols <- colnames(prop_all_nounknown)[!colnames(prop_all_nounknown) %in% c("cellstate","donor_radiation")]
prop_all_nounknown_long <- gather(prop_all_nounknown, tool, proportion, gathercols)
prop_all_nounknown_long$tool <- factor(prop_all_nounknown_long$tool,levels = rownames(metric))
prop_all_nounknown_long$donor_radiation <- factor(prop_all_nounknown_long$donor_radiation,level = donor_radiation_bysize)
prop_all_nounknown_long$cellstate <- factor(prop_all_nounknown_long$cellstate, levels = c("MESlike" ,"OPClike","AClike" , "NPClike", "unknown" ))
plot.prop.nounknown <- ggplot(prop_all_nounknown_long, aes(fill=cellstate, y=proportion, x=donor_radiation)) + 
  geom_bar(position="fill", stat="identity") +
  facet_wrap(~tool) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1,size = 3)) +
  labs(title = "Cellstate annotaion",
       subtitle = paste0("analysed group: ","both"," ; ",run),
       caption = paste0(
                         "metric = ",chosen_metric,"\n",
                         "criteria = ",paste(score_name[pick],collapse = ": "),";  ",
                         "weight = ",paste(weights[pick],collapse = ":"))) +
  scale_fill_manual(values = cellstate_colors)
  

```

```{r}
library(gridExtra)
library(gtable)

# Set theme to allow for plotmath expressions
#tt <- ttheme_default(colhead=list(fg_params = list(parse=TRUE)))
#tbl <- tableGrob(SummaryTable, rows=NULL, theme=tt)
tbl <- rownames_to_column(metric[,c("score","rank")],var = "tool")
tbl.gnob <- tableGrob(tbl,rows = NULL,theme=ttheme_default(base_size = 4,padding = unit(c(1, 1), "mm")) )


gp.prop <- ggplotGrob(plot.prop)
gp.prop.table <- gtable_add_grob(x = gp.prop,
                       grobs = tbl.gnob,
                       t = 18, 
                       l = 17 )

gp.count <- ggplotGrob(plot.count)
gp.count.table <- gtable_add_grob(x = gp.count,
                       grobs = tbl.gnob,
                       t = 18, 
                       l = 17 )

gp.prop.nounknown <- ggplotGrob(plot.prop.nounknown)
gp.prop.nounknown.table <- gtable_add_grob(x = gp.prop.nounknown,
                       grobs = tbl.gnob,
                       t = 18, 
                       l = 17 )


gp.count.nounknown <- ggplotGrob(plot.count.nounknown)
gp.count.nounknown.table <- gtable_add_grob(x = gp.count.nounknown,
                       grobs = tbl.gnob,
                       t = 18, 
                       l = 17 )
```

```{r}
plot(gp.prop.table)
plot(gp.count.table)
plot(gp.prop.nounknown.table)
plot(gp.count.nounknown.table)
```

```{r}
plot(gp.prop.table)
plot(gp.count.table)
plot(gp.prop.nounknown.table)
plot(gp.count.nounknown.table)
```


```{r}
plot(gp.prop.table)
plot(gp.count.table)
plot(gp.prop.nounknown.table)
plot(gp.count.nounknown.table)
```


```{r}
# # Do sankey
# library(ggsankey)
# library(ggplot2)
# library(patchwork)
# library(ggtext)
# my_colors <- c("red", "green", "blue", "gray", "purple", "orange")
# plots_list <- list()
# 
# 
# 
# for (i in levels(anno_cellstate_meta_control_sortcol$donor_id)) {
#   anno_cellstate_meta_each <- anno_cellstate_meta_control_sortcol[anno_cellstate_meta_control_sortcol$donor_id== i,]
#   anno_cellstate_meta_each <- anno_cellstate_meta_each %>% dplyr::select(-1)
#   all.sankey <- anno_cellstate_meta_each
#   colnames(all.sankey) <- gsub("_no_unknown","",colnames(all.sankey))
#   df <- all.sankey %>%
#     make_long(colnames(all.sankey))
# 
#   # Chart 1
#   pl <- ggplot(df, aes(
#     x = x,
#     next_x = next_x,
#     node = node,
#     next_node = next_node,
#     fill = factor(node),
#     label = node
#   ))
#   pl <- pl + geom_sankey(
#     flow.alpha = 0.5,
#     node.color = "black",
#     show.legend = FALSE
#   )
#   #pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
#   pl <- pl + theme_bw()
#   pl <- pl + theme(legend.position = "none")
#   pl <- pl + theme(
#     axis.title = element_blank(),
#     axis.text.y = element_blank(),
#     axis.ticks = element_blank(),
#     axis.text.x = element_blank(),
#     panel.grid = element_blank()
#   )
# 
#   pl <- pl + labs(subtitle = paste(i,"; ",
#                                    round(nrow(anno_cellstate_meta_each)*100/nrow(anno_cellstate_meta),digits = 2),"%",
#                                    sep = ""))
#   pl <- pl + labs(fill = "Nodes")
#   pl <- pl + scale_fill_manual(values = my_colors)
#   plots_list[[i]] <- pl
# }
# 
# combined_plot <- wrap_plots(plots_list, ncol = 6)
# 
# 
# # Assuming 'my_colors' is your color vector and 'df' is your data frame
# # Map colors to factor levels
# color_mapping <- setNames(my_colors, levels(factor(df$node)))
# 
# # Construct the caption string dynamically
# caption_text <- paste(sapply(names(color_mapping), function(node) {
#   sprintf("<span style='color: %s;'>%s</span>", color_mapping[node], node)
# }), collapse = " ")
# 
# combined_plot + plot_annotation(
#     title = paste0(paste(setdiff(levels(factor(df$node)),"unknown"),collapse = ", ") ," cell states","; ",unknown,"; ",run),
#     subtitle = caption_text,
#     caption = paste(colnames(anno_cellstate_meta_control_sortcol)[-1],collapse = "; "),
#     theme = theme(plot.subtitle = element_markdown())
# )
# 

```



 
#cv (unused)
```{r}
# # Assuming count_all is your data frame with columns: cellstate, donor_id, tool1, tool2, ...
# 
# # Load required libraries
# library(dplyr)
# 
# # Function to calculate Coefficient of Variation (CV)
# cv <- function(x) {
#   sd_val <- sd(x)
#   mean_val <- mean(x)
#   cv_result <- sd_val / mean_val * 100  # Multiply by 100 for percentage
#   return(cv_result)
# }
# 
# # Identify the column indices for cell types
# celltype_columns <- 3:ncol(count_all)  # Assuming cell type proportions start from the third column
# 
# # Print the column names to check
# print(colnames(count_all))
# 
# # Print the indices to check
# print(celltype_columns)
# # Apply CV function to each cell type column
# tool_cv <- data.frame(cellstate =levels(count_all$cellstate))
# tool_cv$cellstate <- as.factor(tool_cv$cellstate)  
# for (i in 3:ncol(count_all)) {
#   prop_tool <- count_all[,c(1,2,i)]
#   tool_name <- colnames(prop_tool)[3]
#   colnames(prop_tool)[3] <- "tool"
#   prop_tool <-  prop_tool %>% group_by(cellstate) %>% summarize(
#   avg_cv = cv(tool))
#   colnames(prop_tool)[2] <- tool_name
#   tool_cv <- merge(tool_cv,prop_tool,by = "cellstate")
# } 
# 
# tool_cv

```

