```{r}
library(here)
setwd(here())
library(tidyverse)
```


```{r}
#Import Data
# Parameter
# cell input to be analyse

object <- "all"

sigs <- c("6metamodules", "4metamodules_new_50", "3metamodules_new_50", "4metamodules_new_50_mes")



# For reference based
merges <- c("6metamodules", "4_merge_metamodules", "4_merge_metamodules_3celltypes", "4_merge_metamodules_mes")

# 4  subtype
sig <- sigs[2]
merge <- merges[2]

# import all data
# marker.based
sc.type <- read.csv(paste0("output/scType_", object, "_", sig, ".csv"), row.names = 1)
sc.type <- sc.type[1]

scina <- read.csv(paste0("output/SCINA_", object, "_", sig, ".csv"), row.names = 1)
scina <- scina[1]
# ref-based
clustify.r <- read.csv(paste0("output/clustifyr_", object, "_", merge, ".csv"), row.names = 1)
clustify.r <- clustify.r[1]
scid <- read.csv(paste0("output/scID_", object, "_", merge,"_allassigned",".csv"), row.names = 1)
scid <- scid[2] #need to choose the 2nd col as the allassined version is in there
anno <- bind_cols(sc.type, scina, clustify.r, scid)

colnames(anno) <- paste(colnames(anno), sig, sep = "_")

anno[] <- lapply(anno, function(x) gsub("\\.new$", "like", x))
View(anno)
```

```{r}
#Read result
all <- read.csv("output/consensus_all_4metamodules_new_50_weighted_bulk.csv",row.names = 1)
```







```{r}
aitchison.dist <- dist(all.control.clr)

mds_result <- cmdscale(aitchison.dist, k = 2) # k = 2 for 2D visualization

# Convert the result to a data frame for plotting
mds_df <- as.data.frame(mds_result)

# Rename the columns for clarity
colnames(mds_df) <- c("MDS1", "MDS2")
mds_df
```


```{r}
# Plot the MDS result using ggplot2
ggplot(mds_df, aes(x = `MDS1`, y = `MDS2`)) +
  geom_point() +
  labs(x = "MDS1", y = "MDS2") +
  ggtitle("MDS Plot")
```







