```{r}
library(here)
library(tibble)
library(dplyr)
library(data.table)

```

```{r}
#Set working directory
setwd(here())
source("script/function.R")
```
```{r}
# Parameter
source("script/parameter.R")

```
```{r}
#set unknown 
#choose 1 if with unknown, 2 if w/o unknown
unknown <- unknowns[1]

#choose 1 if each, 2 if whole
#set whole vs each
run_each <- run_eachs[1]
```
```{r}
#choose what to analyse

pick <- 4
sig <- sigs[pick]
merge <- merges[pick]


#run_each <- run_eachs[2]
if (run_each) {
  run <- runs[1]
} else {
  run <- runs[2]
}

possible_3celltpyes <- c("AClike","NPClike","OPClike","unknown","tie")
```



```{r}
# import all data
# marker.based
sc.type <- read.csv(paste0("output/scType_", object, "_", sig,"_",run, ".csv"), row.names = 1)
sc.type <- sc.type[,paste0("scType",unknown) ,drop = FALSE]

scina <- read.csv(paste0("output/SCINA_", object, "_", sig,"_",run, ".csv"), row.names = 1)
scina <- scina[,paste0("SCINA",unknown) ,drop = FALSE]


# add full option
sc.sorter <- read.csv(paste0("output/scsorter_", object, "_", sig, "_",run,".csv"), row.names = 1)
sc.sorter$scSorter_no_unknown <- NA
sc.sorter <- sc.sorter[,paste0("scSorter",unknown) ,drop = FALSE]
```


```{r}
#unknown <- unknowns[1]
# ref-based
clustify.r <- read.csv(paste0("output/clustifyr_", object, "_", merge, "_",run,".csv"), row.names = 1)
#clustify.r <- clustify.r[,paste0("clustifyr_ref",unknown) ,drop = FALSE]
clustify.r <- clustify.r[,paste0("clustifyr_ref") ,drop = FALSE]

scid <- read.csv(paste0("output/scID_", object, "_", merge,"_allassigned","_",run,".csv"), row.names = 1)
scid <- scid[,paste0("scID",unknown) ,drop = FALSE]
```


```{r}
# Add Full option
sc.pred <- read.csv(paste0("output/scpred_", object, "_", merge, "_",run, ".csv"), row.names = 1)
sc.pred <- sc.pred[,2:1]
colnames(sc.pred) <- c("scPred",paste0("scPred",unknowns[2]))
sc.pred <- sc.pred[,paste0("scPred",unknown) ,drop = FALSE]

single.r <- read.csv(paste0("output/singleR_", object, "_", merge, "_",run, ".csv"), row.names = 1)
single.r <- single.r[,2:1]
colnames(single.r) <- c("singleR",paste0("singleR",unknowns[2]))
single.r[is.na(single.r$singleR),"singleR"] <- "unknown"
single.r <- single.r[,paste0("singleR",unknown) ,drop = FALSE]

scibet <- read.csv(paste0("output/scibet_", object, "_", merge,  "_",run,".csv"), row.names = 1)
scibet$scibet_no_unknown <- scibet$scibet #no unknown by default
scibet <- scibet[,paste0("scibet",unknown) ,drop = FALSE]

chetah <- read.csv(paste0("output/CHETAH_", object, "_", merge, "_",run, ".csv"), row.names = 1)
chetah$CHETAH_no_unknown <- chetah$CHETAH
chetah <- chetah[,paste0("CHETAH",unknown) ,drop = FALSE]

scmap_cluster <- read.csv(paste0("output/scmap_cluster_", object, "_", merge,  "_",run,".csv"), row.names = 1)
scmap_cluster$scmap_cluster_no_unknown <- scmap_cluster$scmap_cluster #cannot tweak to have no unknown
scmap_cluster <- scmap_cluster[,paste0("scmap_cluster",unknown) ,drop = FALSE]

scmap_cell <- read.csv(paste0("output/scmap_cell_", object, "_", merge,  "_",run,".csv"), row.names = 1)
scmap_cell$scmap_cell_no_unknown <- scmap_cell$scmap_cell #cannot tweak to have no unknown
scmap_cell <- scmap_cell[,paste0("scmap_cell",unknown) ,drop = FALSE]
```

```{r}
sc.type;scina; clustify.r;scid;sc.sorter;sc.pred;scibet;chetah;single.r;scmap_cluster;scmap_cluster
```


```{r}
anno <- bind_cols(sc.type, scina, clustify.r,scid)

#full option
#anno <- bind_cols(sc.type, scina, clustify.r,scid,sc.pred,scibet,chetah,single.r,scmap_cluster,scmap_cell)

#colnames(anno) <- paste(colnames(anno), sig, sep = "_")

anno[] <- lapply(anno, function(x) gsub("\\.new$", "like", x))
anno[] <- lapply(anno, function(x) gsub("Unknown", "unknown", x))
anno[] <- lapply(anno, function(x) gsub("unassigned", "unknown", x))
```

```{r}
anno
```




```{r}
# Do sankey
library(ggsankey)
library(ggplot2)


all.sankey <- anno
colnames(all.sankey) <- gsub("_no_unknown","",colnames(all.sankey))
df <- all.sankey %>%
  make_long(colnames(all.sankey))

# Chart 1
pl <- ggplot(df, aes(
  x = x,
  next_x = next_x,
  node = node,
  next_node = next_node,
  fill = factor(node),
  label = node
))
pl <- pl + geom_sankey(
  flow.alpha = 0.5,
  node.color = "black",
  show.legend = FALSE
)
pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
pl <- pl + theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl + theme(
  axis.title = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank()
)

# pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = paste(object, sig,run, unknown,sep = "; "))
pl <- pl + labs(fill = "Nodes")
pl
```
```{r}
# MES
pick <- 1
#run_each <- run_eachs[1]

sig <- sigs[pick]
merge <- merges[pick]
if (run_each) {
  run <- runs[1]
} else {
  run <- runs[2]
}

# import all data
# marker.based
sc.type <- read.csv(paste0("output/scType_", object, "_", sig, "_",run,".csv"), row.names = 1)
sc.type <- sc.type[,paste0("scType") ,drop = FALSE]
sc.type[] <- lapply(sc.type, function(x) gsub("Unknown", "Non_MESlike", x))


scina <- read.csv(paste0("output/SCINA_", object, "_", sig,  "_",run,".csv"), row.names = 1)
scina <- scina[,paste0("SCINA") ,drop = FALSE]
scina[] <- lapply(scina, function(x) gsub("unknown", "Non_MESlike", x))

# ref-based
clustify.r <- read.csv(paste0("output/clustifyr_", object, "_", merge, "_",run, ".csv"), row.names = 1)
#clustify.r <- clustify.r[,paste0("clustifyr_ref",unknown) ,drop = FALSE]
clustify.r <- clustify.r[,paste0("clustifyr_ref") ,drop = FALSE]
clustify.r[] <- lapply(clustify.r, function(x) gsub("not_labeled", "Non_MESlike", x))

scid <- read.csv(paste0("output/scID_", object, "_", merge,"_allassigned", "_",run,".csv"), row.names = 1)
scid <- scid[,paste0("scID",unknown) ,drop = FALSE]
#scid <- scid[,paste0("scID",unknowns[2]) ,drop = FALSE]

scid[] <- lapply(scid, function(x) gsub("not_labeled", "Non_MESlike", x))

#scid[] <- lapply(scid, function(x) gsub("unassigned", "unknown", x))
scid[] <- lapply(scid, function(x) gsub("unassigned", "Non_MESlike", x))
```

```{r}
# add full option
# sc.sorter <- read.csv(paste0("output/scsorter_", object, "_", sig, "_",run,".csv"), row.names = 1)
# sc.sorter$scSorter_no_unknown <- NA
# sc.sorter <- sc.sorter[,paste0("scSorter",unknown) ,drop = FALSE]


# # Add Full option
# sc.pred <- read.csv(paste0("output/scpred_", object, "_", merge, "_",run, ".csv"), row.names = 1)
# sc.pred <- sc.pred[,2:1]
# colnames(sc.pred) <- c("scPred",paste0("scPred",unknowns[2]))
# sc.pred <- sc.pred[,paste0("scPred",unknown) ,drop = FALSE]
# 
# single.r <- read.csv(paste0("output/singleR_", object, "_", merge, "_",run, ".csv"), row.names = 1)
# single.r <- single.r[,2:1]
# colnames(single.r) <- c("singleR",paste0("singleR",unknowns[2]))
# single.r[is.na(single.r$singleR),"singleR"] <- "unknown"
# single.r <- single.r[,paste0("singleR",unknown) ,drop = FALSE]
# 
# scibet <- read.csv(paste0("output/scibet_", object, "_", merge,  "_",run,".csv"), row.names = 1)
# scibet$scibet_no_unknown <- scibet$scibet
# scibet <- scibet[,paste0("scibet",unknown) ,drop = FALSE]
# 
# chetah <- read.csv(paste0("output/CHETAH_", object, "_", merge, "_",run, ".csv"), row.names = 1)
# chetah$CHETAH_no_unknown <- chetah$CHETAH
# chetah <- chetah[,paste0("CHETAH",unknown) ,drop = FALSE]
# 
# scmap_cluster <- read.csv(paste0("output/scmap_cluster_", object, "_", merge,  "_",run,".csv"), row.names = 1)
# scmap_cluster$scmap_cluster_no_unknown <- NA
# scmap_cluster <- scmap_cluster[,paste0("scmap_cluster",unknown) ,drop = FALSE]
# 
# scmap_cell <- read.csv(paste0("output/scmap_cell_", object, "_", merge,  "_",run,".csv"), row.names = 1)
# scmap_cell$scmap_cell_no_unknown <- NA
# scmap_cell <- scmap_cell[,paste0("scmap_cell",unknown) ,drop = FALSE]
```
```{r}
anno_mes <- bind_cols(sc.type, scina, clustify.r,scid)

#full option

#anno_mes <- bind_cols(sc.type, scina, clustify.r,scid,sc.pred,scibet,chetah,single.r,scmap_cluster,scmap_cell)


anno_mes[] <- lapply(anno_mes, function(x) gsub("\\.new$", "like", x))


anno_mes[] <- lapply(anno_mes, function(x) gsub("not_labeled", "Non_MESlike", x))

#anno_mes[] <- lapply(anno_mes, function(x) gsub("unassigned", "unknown", x))
anno_mes[] <- lapply(anno_mes, function(x) gsub("unassigned", "Non_MESlike", x))

anno_mes
```




```{r}
# Do sankey
library(ggsankey)
library(ggplot2)


all.sankey <- anno_mes

df <- all.sankey %>%
  make_long(colnames(all.sankey))

# Chart 1
pl <- ggplot(df, aes(
  x = x,
  next_x = next_x,
  node = node,
  next_node = next_node,
  fill = factor(node),
  label = node
))
pl <- pl + geom_sankey(
  flow.alpha = 0.5,
  node.color = "black",
  show.legend = FALSE
)
pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
pl <- pl + theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl + theme(
  axis.title = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank()
)

# pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = paste(object, sig, run,sep = "; "))
pl <- pl + labs(fill = "Nodes")
pl
```



```{r}
# Merge information
anno <- anno[order(rownames(anno)), ]
anno_mes <- anno_mes[order(rownames(anno_mes)), ]

annon_mes_edited <- anno_mes %>% mutate(across(everything(), ~na_if(., "Non_MESlike")))
anno_merge <- mapply(paste, anno, annon_mes_edited, MoreArgs = list(sep = "_"))


anno_merge <- as.data.frame(anno_merge)
rownames(anno_merge) <- rownames(anno_mes)

anno_merge[] <- lapply(anno_merge, function(x) gsub("_NA", "", x))
```
```{r}
# Do sankey
library(ggsankey)
library(ggplot2)



all.sankey <- anno_merge

df <- all.sankey %>%
  make_long(colnames(all.sankey))
df

# Chart 1
pl <- ggplot(df, aes(
  x = x,
  next_x = next_x,
  node = node,
  next_node = next_node,
  fill = factor(node),
  label = node
))
pl <- pl + geom_sankey(
  flow.alpha = 0.5,
  node.color = "black",
  show.legend = FALSE
)
pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
pl <- pl + theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl + theme(
  axis.title = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank()
)

# pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = paste(object, sig, sep = "; "))
pl <- pl + labs(fill = "Nodes")
pl
```

```{r}
#add gbm metadata
gbm.meta <- read.csv("output/gbm_meta.csv",row.names = 1)
gbm.meta
anno_merge_radiation <- cbind(anno_merge,gbm.meta[,"radiation"])

anno_merge_radiation
```

```{r}
# Sankey on control
# Do sankey
library(ggsankey)
library(ggplot2)



all.sankey <- anno_merge_radiation[anno_merge_radiation$`gbm.meta[, "radiation"]` == "control",1:4]

df <- all.sankey %>%
  make_long(colnames(all.sankey))
df

# Chart 1
pl <- ggplot(df, aes(
  x = x,
  next_x = next_x,
  node = node,
  next_node = next_node,
  fill = factor(node),
  label = node
))
pl <- pl + geom_sankey(
  flow.alpha = 0.5,
  node.color = "black",
  show.legend = FALSE
)
pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
pl <- pl + theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl + theme(
  axis.title = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank()
)

# pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = paste(object, sig, sep = "; "),
                subtitle = "control")
pl <- pl + labs(fill = "Nodes")
pl
```
```{r}
# Sankey on control
# Do sankey
library(ggsankey)
library(ggplot2)



all.sankey <- anno_merge_radiation[anno_merge_radiation$`gbm.meta[, "radiation"]` == "radiated",1:4]

df <- all.sankey %>%
  make_long(colnames(all.sankey))
df

# Chart 1
pl <- ggplot(df, aes(
  x = x,
  next_x = next_x,
  node = node,
  next_node = next_node,
  fill = factor(node),
  label = node
))
pl <- pl + geom_sankey(
  flow.alpha = 0.5,
  node.color = "black",
  show.legend = FALSE
)
pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
pl <- pl + theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl + theme(
  axis.title = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank()
)

# pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = paste(object, sig, sep = "; "),
                subtitle = "radiated")
pl <- pl + labs(fill = "Nodes")
pl
```