
```{r}
library(dplyr)
library(here)
```


```{r}
#Set working directory
setwd(here())
source("script/function.R")
```
```{r}
# Parameter
# cell input to be analyse

object <- "all"

sigs <- c( "4metamodules_new_50_mes","2metamodules_NPC_OPC", "3metamodules_new_50", "4metamodules_new_50","npcopc_ac_mes","npcopc_acmes")



# For reference based
merges <- c("4_merge_metamodules_mes","2_merge_metamodules",  "4_merge_metamodules_3celltypes","4_merge_metamodules","npcopc_ac_mes","npcopc_acmes")


unknowns <- c("","_no_unknown")


run_eachs <- c(TRUE,FALSE)
runs <- c("each","whole")

```
```{r}
#set unknown 
unknown <- unknowns[1]

#set whole vs each
run_each <- run_eachs[1]

#3 celltype

pick <- 6

sig <- sigs[pick]
merge <- merges[pick]


#run_each <- run_eachs[2]
if (run_each) {
  run <- runs[1]
} else {
  run <- runs[2]
}

possible_3celltpyes <- c("AClike","NPClike","OPClike","unknown","tie")
```

```{r}
gbm.meta <- read.csv("output/gbm_meta.csv",row.names = 1)
gbm.meta
```

```{r}
# import all data
# marker.based
sc.type <- read.csv(paste0("output/scType_", object, "_", sig,"_",run, ".csv"), row.names = 1)
sc.type <- sc.type[,paste0("scType",unknown) ,drop = FALSE]

scina <- read.csv(paste0("output/SCINA_", object, "_", sig,"_",run, ".csv"), row.names = 1)
scina <- scina[,paste0("SCINA",unknown) ,drop = FALSE]


# # add full option
# sc.sorter <- read.csv(paste0("output/scsorter_", object, "_", sig, "_",run,".csv"), row.names = 1)
# sc.sorter$scSorter_no_unknown <- NA
# sc.sorter <- sc.sorter[,paste0("scSorter",unknown) ,drop = FALSE]
```


```{r}
#unknown <- unknowns[1]
# ref-based
clustify.r <- read.csv(paste0("output/clustifyr_", object, "_", merge, "_",run,".csv"), row.names = 1)
#clustify.r <- clustify.r[,paste0("clustifyr_ref",unknown) ,drop = FALSE]
clustify.r <- clustify.r[,paste0("clustifyr_ref") ,drop = FALSE]

scid <- read.csv(paste0("output/scID_", object, "_", merge,"_allassigned","_",run,".csv"), row.names = 1)
scid <- scid[,paste0("scID",unknown) ,drop = FALSE]
```


```{r}
# Add Full option
# sc.pred <- read.csv(paste0("output/scpred_", object, "_", merge, "_",run, ".csv"), row.names = 1)
# sc.pred <- sc.pred[,2:1]
# colnames(sc.pred) <- c("scPred",paste0("scPred",unknowns[2]))
# sc.pred <- sc.pred[,paste0("scPred",unknown) ,drop = FALSE]
# 
# single.r <- read.csv(paste0("output/singleR_", object, "_", merge, "_",run, ".csv"), row.names = 1)
# single.r <- single.r[,2:1]
# colnames(single.r) <- c("singleR",paste0("singleR",unknowns[2]))
# single.r[is.na(single.r$singleR),"singleR"] <- "unknown"
# single.r <- single.r[,paste0("singleR",unknown) ,drop = FALSE]
# 
# scibet <- read.csv(paste0("output/scibet_", object, "_", merge,  "_",run,".csv"), row.names = 1)
# scibet$scibet_no_unknown <- scibet$scibet #no unknown by default
# scibet <- scibet[,paste0("scibet",unknown) ,drop = FALSE]
# 
# chetah <- read.csv(paste0("output/CHETAH_", object, "_", merge, "_",run, ".csv"), row.names = 1)
# chetah$CHETAH_no_unknown <- chetah$CHETAH
# chetah <- chetah[,paste0("CHETAH",unknown) ,drop = FALSE]
# 
# scmap_cluster <- read.csv(paste0("output/scmap_cluster_", object, "_", merge,  "_",run,".csv"), row.names = 1)
# scmap_cluster$scmap_cluster_no_unknown <- scmap_cluster$scmap_cluster #cannot tweak to have no unknown
# scmap_cluster <- scmap_cluster[,paste0("scmap_cluster",unknown) ,drop = FALSE]
# 
# scmap_cell <- read.csv(paste0("output/scmap_cell_", object, "_", merge,  "_",run,".csv"), row.names = 1)
# scmap_cell$scmap_cell_no_unknown <- scmap_cell$scmap_cell #cannot tweak to have no unknown
# scmap_cell <- scmap_cell[,paste0("scmap_cell",unknown) ,drop = FALSE]
```

```{r}
#sc.type;scina; clustify.r;scid;sc.sorter;sc.pred;scibet;chetah;single.r;scmap_cluster;scmap_cluster
```


```{r}
anno_3subtype <- bind_cols(sc.type, scina, clustify.r,scid)

#full option
#anno_3subtype <- bind_cols(sc.type, scina, clustify.r,scid,sc.pred,scibet,chetah,single.r,scmap_cluster,scmap_cell)

#colnames(anno_3subtype) <- paste(colnames(anno_3subtype), sig, sep = "_")
anno_3subtype[] <- lapply(anno_3subtype, function(x) gsub("NPC_OPC$", "NPC_OPClike", x))
anno_3subtype[] <- lapply(anno_3subtype, function(x) gsub("AC$", "AClike", x))
anno_3subtype[] <- lapply(anno_3subtype, function(x) gsub("MES$", "MESlike", x))
anno_3subtype[] <- lapply(anno_3subtype, function(x) gsub("AC_MES$", "AC_MESlike", x))
anno_3subtype[] <- lapply(anno_3subtype, function(x) gsub("\\.new$", "like", x))
anno_3subtype[] <- lapply(anno_3subtype, function(x) gsub("Unknown", "unknown", x))
anno_3subtype[] <- lapply(anno_3subtype, function(x) gsub("unassigned", "unknown", x))
```

```{r}
anno_3subtype_meta <- cbind(gbm.meta$donor_radiation,anno_3subtype)
colnames(anno_3subtype_meta)[1] <- "donor_radiation"
anno_3subtype_meta$donor_radiation <- as.factor(anno_3subtype_meta$donor_radiation)

anno_3subtype_meta
```

```{r}
# Do sankey
library(ggsankey)
library(ggplot2)
library(patchwork)
library(ggtext)




my_colors <- c("red", "green", "blue", "gray", "purple", "orange") 
plots_list <- list()

for (i in levels(anno_3subtype_meta$donor_radiation)) {
  anno_3subtype_meta_each <- anno_3subtype_meta[anno_3subtype_meta$donor_radiation == i,]
  anno_3subtype_meta_each <- anno_3subtype_meta_each[,-1]
  all.sankey <- anno_3subtype_meta_each
  colnames(all.sankey) <- gsub("_no_unknown","",colnames(all.sankey))
  df <- all.sankey %>%
    make_long(colnames(all.sankey))
  
  # Chart 1
  pl <- ggplot(df, aes(
    x = x,
    next_x = next_x,
    node = node,
    next_node = next_node,
    fill = factor(node),
    label = node
  ))
  pl <- pl + geom_sankey(
    flow.alpha = 0.5,
    node.color = "black",
    show.legend = FALSE
  )
  #pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
  pl <- pl + theme_bw()
  pl <- pl + theme(legend.position = "none")
  pl <- pl + theme(
    axis.title = element_blank(),
    axis.text.y = element_blank(),
    axis.ticks = element_blank(),
    axis.text.x = element_blank(),
    panel.grid = element_blank()
  )
  
  pl <- pl + labs(subtitle = paste(i,"; ",
                                   round(nrow(anno_3subtype_meta_each)*100/nrow(anno_3subtype_meta),digits = 2),"%",
                                   sep = ""))
  pl <- pl + labs(fill = "Nodes")
  pl <- pl + scale_fill_manual(values = my_colors)
  plots_list[[i]] <- pl 
}

combined_plot <- wrap_plots(plots_list, ncol = 6)


# Assuming 'my_colors' is your color vector and 'df' is your data frame
# Map colors to factor levels
color_mapping <- setNames(my_colors, levels(factor(df$node)))

# Construct the caption string dynamically
caption_text <- paste(sapply(names(color_mapping), function(node) {
  sprintf("<span style='color: %s;'>%s</span>", color_mapping[node], node)
}), collapse = " ")

combined_plot + plot_annotation(
    title = paste0(paste(setdiff(levels(factor(df$node)),"unknown"),collapse = ", ") ," cell states","; ",unknown,"; ",run),
    subtitle = caption_text,
    caption = paste(colnames(anno_3subtype),collapse = "; "),
    theme = theme(plot.subtitle = element_markdown())
)

```



