```{r}

library(here)
library(tibble)
library(dplyr)
library(data.table)
library(Seurat)
library(parallel)
library(ggh4x)
library(tidyr)

#Set working directory
setwd(here())
source("script/function.R")
source("script/parameter.R")
```
#new

```{r}

#set unknown 
#choose 1 if with unknown, 2 if w/o unknown
unknown <- unknowns[1]

#choose 1 if each, 2 if whole
#set whole vs each
run_each <- run_eachs[1]

#choose what to analyse

pick <- 4
merge <- merges[pick]

#run_each <- run_eachs[2]
if (run_each) {
  run <- runs[1]
} else {
  run <- runs[2]
}

```


#post annotation analysis

```{r}
#load data
anno_score <- fread(file = paste("output/annotation/annotation",merge,run,unknown,".csv",sep = "_"))
anno_score_short <- fread(file = paste("output/annotation/annotation_short",merge,run,unknown,".csv",sep = "_"))
gbm.meta <- read.csv("output/gbm_meta.csv", row.names = 1)
```

```{r}
anno_score_short
```

```{r}
anno_score[,consensus_threshold := consensus]

anno_score[confidence < 0.5 ,consensus_threshold := "unknown" ]
#anno_score[confidence == 0 ,consensus_threshold := "unknown" ]
```

```{r}
anno_score$consensus_threshold <- as.character(anno_score$consensus_threshold)
possible_cellstate <- unique(unname(unlist(anno_score[,c("stochastic_consensus","consensus_with_stochastic_of_tie","consensus_threshold")])))

possible_cellstate_with_unknown <- c(setdiff(possible_cellstate,"unknown"),"unknown")
possible_cellstate_with_unassign <- c(setdiff(possible_cellstate,"unassign"),"unassign")
possible_cellstate_with_unassign_tie <- c(setdiff(possible_cellstate,c("unassign","tie")),"unassign","tie")
possible_cellstate_with_tie <- c(setdiff(possible_cellstate,"tie"),"tie")
```

```{r}
anno_score$consensus_threshold <- factor(anno_score$consensus_threshold ,level = possible_cellstate_with_unknown)
```

```{r}
anno_score_meta <- merge(anno_score,rownames_to_column(gbm.meta,var = "rn"),by = "rn")
```



#consensus
```{r}
plot(x = anno_score$agreement,y = anno_score$confidence)
plot(x = anno_score$known,y = anno_score$confidence)
plot(x = anno_score$known,y = anno_score$agreement)
```

```{r}
# Assuming you have a predefined set of levels for 'consensus'
#anno_score_meta$consensus_threshold <- factor(anno_score_meta$consensus_threshold,levels = possible_cellstate_with_unknown)
# Your original code with complete
```


```{r}
anno_score_meta
```


```{r}
count_consensus <- anno_score_meta %>%
  group_by(radiation, donor_id, consensus_threshold) %>%
  summarise(count_consensus = n()) %>%
  complete(consensus_threshold, fill = list(count_consensus = 0))


```



```{r}
mean_score <- anno_score_meta %>%
  group_by(radiation, donor_id) %>%
  summarise(confidence = mean(confidence),
            agreement = mean(agreement),
            known_prop = mean(known),
            cell_number = n())

mean_score
```


```{r}
ggplot(mean_score,
         aes(x = agreement, y = confidence, size = cell_number, color = known_prop)) +
    geom_point() +
    labs(title = "mean Score from each donor_id") +
    scale_color_continuous(limits = c(0, 1)) +  # Set color scale limits
    scale_size_continuous(limits = c(100, 4000))  +  # Set size scale limits
    facet_wrap(~radiation)
```

```{r}
mean_score_cellstate <- anno_score_meta %>%
  group_by(radiation, donor_id,consensus_threshold) %>%
  summarise(confidence = mean(confidence),
            agreement = mean(agreement),
            known_prop = mean(known),
            cell_number = n())

mean_score_cellstate
```
```{r}
ggplot(mean_score_cellstate,
         aes(x = agreement, y = confidence, size = cell_number, color = known_prop)) +
    geom_point() +
    labs(title = "mean Score from each donor_id") +
     # facet_grid(radiation ~ consensus)
    facet_grid(consensus_threshold ~ radiation)
```


```{r}
# Create a 3D scatter plot
library(scatterplot3d)
scatterplot3d(mean_score$agreement, mean_score$confidence, mean_score$known_prop, 
              color = "blue", main = "3D Scatter Plot",
              xlab = "agreement", ylab = "confidence", zlab = "known_prop",
                            grid = TRUE, box = FALSE,type = "h")

text(x = 7, y = 0.5, "confidence", srt = 25)



```

```{r}
consensus_unique <- possible_cellstate_with_unknown
```



```{r}
anno_score_mean <- anno_score_meta[, .(confidence_mean = mean(confidence),
                                            agreement_mean = mean(agreement),
                                            known_mean = mean(known)),
                                    by = c("radiation", "donor_id")]

anno_consensus_count <- dcast(anno_score_meta, formula = donor_id + radiation ~ consensus_threshold,drop = FALSE)
possible_cellstate_with_unknown

anno_consensus_count[, n_cell:= rowSums(.SD),.SDcols = consensus_unique]
anno_consensus_count <- merge(anno_consensus_count,anno_score_mean,by = c("donor_id","radiation"))

anno_consensus_count_long <- melt(anno_consensus_count,id.vars = c("radiation","donor_id","n_cell","confidence_mean","agreement_mean","known_mean"), measure.vars = consensus_unique,variable.name = "consensus_threshold",value.name = "count")


#common
anno_consensus_count_long[,per := count/sum(count),by = c("radiation","donor_id")]
anno_consensus_count_long[, rad_con := paste0(radiation,"(",n_cell,")","\n","[",round(confidence_mean,digits = 2),"/",
                                              round(agreement_mean,digits = 2),"/",
                                              round(known_mean,digits = 2),
                                              "]")]
#anno_consensus_count_long[, don_con := paste0(donor_id," (",round(confidence_mean,digits = 2),")")]




library(grid)
library(randomcoloR)
anno_consensus_count_long$consensus_threshold <- factor(anno_consensus_count_long$consensus_threshold ,
                                                       levels = 
                                                         sort(union(levels(anno_consensus_count_long$consensus_threshold),consensus_unique)))


dummy_data <- data.frame(consensus_threshold = levels(anno_consensus_count_long$consensus_threshold))


set.seed(167)
n <-  length(levels(anno_consensus_count_long$consensus_threshold))
palette <- distinctColorPalette(n)

```
```{r}
cellstate_colors <- c(
  "OPClike" = "#1f77b4",  # Replace 'cellstate1' with actual cellstate names
  "unknown" = "grey",
  "NPClike" = "#2ca02c",
  "AClike" = "#d62728",
  "MESlike" = "#9467bd"
  # Add more colors as needed for each cellstate
)
anno_consensus_count_long$consensus_threshold <-factor(anno_consensus_count_long$consensus_threshold, levels = c("MESlike" ,"OPClike","AClike" , "NPClike", "unknown" ))

anno_consensus_count_long[,]
```


```{r}
p <- ggplot() +
    geom_blank(data = dummy_data, aes(fill = consensus_threshold)) +
    geom_col(data = anno_consensus_count_long, aes(x = sqrt(n_cell)/2, y = per, fill = consensus_threshold, width = sqrt(n_cell))) +
  facet_nested_wrap(~ donor_id + rad_con,strip = strip_nested(size = "variable")) +
  ggtitle("") +
  coord_polar("y", start = 0) +
  theme_void() +

  labs(title = "Cell states proportion", subtitle = paste(object,run,"control vs radiated\n [confidence/agreement/known score)]",sep = "; "), 
       fill = "Cell state") + 
  theme(strip.text = element_text(size = 6)) +
  scale_fill_manual(values = cellstate_colors) 


# Convert the plot to a grob
g <- ggplotGrob(p)

# Define the caption
caption <- 
  #textGrob("", 
  textGrob("pie size based on square root of the number of cells in each group", 
  #textGrob("pie size based on of the number of cells in each group",   
                    x = unit(1, "npc"), y = unit(0.05, "npc"), 
                    hjust = 4, vjust = -5, 
                    gp = gpar(fontface = "italic", col = "black", fontsize = 5)) # Adjust fontsize here
```


```{r}
# Draw the plot and then the caption
grid.newpage()
grid.draw(g)
grid.draw(caption)
```


```{r}
#control vs radiated
```



```{r}
anno_count_sum <- anno_score_meta[, c(lapply(.SD, sum), confidence_mean = mean(confidence),n_cell = as.character(.N)),
                                    .SDcols = consensus_unique,
                                    by = c("radiation")]

anno_count_sum_long <-  melt(anno_count_sum,id.vars = c("radiation","confidence_mean","n_cell"), measure.vars = consensus_unique,variable.name = "consensus_threshold",value.name = "count")

anno_count_sum
anno_count_sum_long

anno_count_sum_long[,per := count/sum(count),by = c("radiation")]

anno_count_sum_long <- anno_count_sum_long[order( radiation,consensus_threshold)]

anno_count_sum_long[,n_cell := as.integer(n_cell)]
anno_count_sum_long[, rad_con := paste0(radiation,"\n","(",round(confidence_mean,digits = 2),")")]





library(grid)
library(randomcoloR)

# set.seed(167)
# n <-  length(unique(anno_count_sum_long$consensus_threshold))
# palette <- distinctColorPalette(n)
anno_count_sum_long$consensus_threshold <-factor(anno_count_sum_long$consensus_threshold, levels = c("MESlike" ,"OPClike","AClike" , "NPClike", "unknown" ))
p <- ggplot(anno_count_sum_long, aes(x = n_cell/2, y = per, fill = consensus_threshold, width = n_cell)) +
  geom_col() +
  facet_nested_wrap(~ rad_con,strip = strip_nested(size = "variable")) +
  ggtitle("") +
  coord_polar("y", start = 0) +
  theme_void() +

  labs(title = "Cell states proportion", subtitle = "all donors; control vs radiated\n (confidence score)",
       fill = "Cell state") +
  theme(strip.text = element_text(size = 6)) +
  scale_fill_manual(values = cellstate_colors)


# Convert the plot to a grob
g <- ggplotGrob(p)

# Define the caption
caption <- textGrob("pie size based on  the number of cells in each group",
                    x = unit(1, "npc"), y = unit(0.05, "npc"),
                    hjust = 2, vjust = -5,
                    gp = gpar(fontface = "italic", col = "black", fontsize = 5)) # Adjust fontsize here

# Draw the plot and then the caption
grid.newpage()
grid.draw(g)
grid.draw(caption)


```
```{r}
anno_count_sum_long
```

```{r}

p1 <- anno_score_meta %>%
  ggplot( aes(x=confidence, fill=consensus_threshold)) +
    geom_histogram( color="#e9ecef", alpha=0.6, position = 'dodge',) +
    labs(fill="")
p1
```

```{r}
p2 <- anno_score_meta %>%
  ggplot( aes(x=confidence, fill=consensus_threshold)) +
    geom_histogram( color="#e9ecef", alpha=0.6, position = 'dodge',bins = 10) +
  facet_wrap(~donor_id) +
    labs(fill="")

p2
```
```{r}
p3 <- anno_score_meta %>%
  ggplot( aes(x=confidence, fill=consensus_threshold)) +
    geom_histogram( color="#e9ecef", alpha=0.6, position = 'dodge',bins = 5) +
  facet_wrap(~donor_radiation) +
    labs(fill="")

p3
```
```{r}
test <- anno_score_meta %>% 
  group_by(consensus_threshold,confidence) %>% 
  summarise(count = n())

# Plotting
ggplot(test, aes(x = confidence, y = count,fill = consensus_threshold, color = consensus_threshold)) +
  geom_point() +
  geom_line() +
  labs(y = "Cell Number")
```

```{r}
anno_score_meta_ggplot <- anno_score_meta %>% 
  group_by(consensus_threshold,confidence,donor_radiation) %>% 
  summarise(count = n()) %>% ungroup()

# Plotting
ggplot(anno_score_meta_ggplot, aes(x = confidence, y = count,fill = consensus_threshold, color = consensus_threshold)) +
  geom_point() +
  geom_line() +
  scale_y_log10() +
  labs(y = "Cell Number (log10)") +
  theme(axis.text.x = element_text(angle = 60, vjust = 1, hjust=1,size = 5)) +
  facet_wrap(~donor_radiation) 
```


#Explore under more sophisticate dimention
```{r}
gbm <- readRDS("output/seurat_gbm_qc")

gbm.list <- SplitObject(gbm, split.by = "donor_radiation")



```

```{r}
library(Seurat)
anno_score_short.df <- data.frame(anno_score_short)

rownames(anno_score_short.df) <- anno_score_short.df$rn
anno_score_short.df$rn <- NULL
anno_score_short.df
gbm <- AddMetaData(object = gbm,metadata = anno_score_short.df)

gbm@meta.data
```

```{r}
set(7)
gbm <- gbm %>%
  NormalizeData() %>%
  ScaleData() %>%
  FindVariableFeatures() %>%
  RunPCA()
```


```{r}
gbm <- gbm %>%  
  RunUMAP(dims = 1:15) 
```
```{r}
DimPlot(gbm,reduction = "umap",group.by = "consensus_threshold")
```
```{r}
DimPlot(gbm,reduction = "umap",group.by = "consensus_threshold",split.by = "donor_radiation",ncol = 5)
```


```{r}
gbm.list <- SplitObject(gbm, split.by = "donor_radiation")
```


```{r}
gbm.list <- lapply(gbm.list,function(x){
  x <- x %>% NormalizeData() %>%
  ScaleData(features = rownames(x)) %>%
  FindVariableFeatures() %>%
  RunPCA() %>%
  RunUMAP(dims = 1:15) %>%
  RunTSNE(dims = 1:15)
  return(x)
})
```

```{r}
gc()
```

```{r}
lapply(gbm.list,
```

```{r}
signatures <- read.csv(file = paste0("output/signature_subtype_", sig,"_","bulk", ".csv"))
gbm.list.signatures <- lapply(gbm.list,function(x){
  x <- x %>% NormalizeData() %>%
  ScaleData(features = rownames(x)) %>%
  FindVariableFeatures() %>%
  RunPCA() %>%
  RunUMAP(dims = 1:15) %>%
  RunTSNE(dims = 1:15)
  return(x)
})
```

#old -->
<!-- ```{r} -->
<!-- anno_mes_each <- fread(file = "output/annotation/annotation_mes_each__.csv") -->
<!-- anno_mes_whole <- fread(file = "output/annotation/annotation_mes_whole__.csv") -->
<!-- anno_3celltypes_each <-fread(file = "output/annotation/annotation_3celltypes_each__.csv") -->
<!-- anno_3celltypes_whole <-fread(file = "output/annotation/annotation_3celltypes_whole__.csv") -->


<!-- anno_all <- Reduce(function(x, y) merge(x, y, by = "rn"),  -->
<!--                    list(anno_mes_each[, .(consensus_mes_each = consensus, confidence_mes_each = confidence, rn)], -->
<!--                         anno_mes_whole[, .(consensus_mes_whole = consensus, confidence_mes_whole = confidence, rn)], -->
<!--                         anno_3celltypes_each[, .(consensus_3celltypes_each = consensus, confidence_3celltypes_each = confidence, rn)], -->
<!--                         anno_3celltypes_whole[, .(consensus_3celltypes_whole = consensus, confidence_3celltypes_whole = confidence, rn)])) -->
<!-- gsub() -->
<!-- anno_all[,.SD := gsub] -->

<!-- anno_all -->


<!-- ``` -->

<!-- ```{r} -->
<!-- #load gbm data -->
<!-- gbm <- readRDS("output/seurat_gbm_qc") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- gbm <- AddMetaData(gbm,metadata =  -->
<!--               data.frame(anno_all,row.names = 1)) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- gbm <- AddMetaData(gbm, metadata = anno_3subtype) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- gbm@meta.data -->
<!-- ``` -->


<!-- ```{r} -->
<!-- DimPlot(gbm,reduction = "umap",group.by = "scType",split.by = "radiation") -->
<!-- DimPlot(gbm,reduction = "umap",group.by = "SCINA",split.by = "radiation") -->
<!-- DimPlot(gbm,reduction = "umap",group.by = "clustifyr_ref",split.by = "radiation") -->
<!-- DimPlot(gbm,reduction = "umap",group.by = "scID",split.by = "radiation") -->
<!-- ``` -->

<!-- ```{r} -->

<!-- ``` -->

<!-- ```{r} -->
<!-- set.seed(123) -->
<!-- #For seurat qc file -->
<!-- gbm <- NormalizeData(gbm) -->
<!-- gbm <- ScaleData(gbm) -->
<!-- gbm <- FindVariableFeatures(gbm) -->
<!-- gbm <- RunPCA(gbm) -->
<!-- gbm <- RunUMAP(gbm,dims = 1:20) -->
<!-- gbm <- RunTSNE(gbm,dims = 1:20) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- DimPlot(gbm,reduction = "umap",group.by = "donor_id",split.by = "radiation") -->
<!-- DimPlot(gbm,reduction = "umap",group.by = "consensus_3celltypes_each",split.by = "radiation") -->
<!-- DimPlot(gbm,reduction = "umap",group.by = "consensus_3celltypes_whole",split.by = "radiation") -->
<!-- ``` -->


<!-- ```{r} -->
<!-- DimPlot(gbm,reduction = "umap",group.by = "consensus_3celltypes_whole",split.by = "donor_radiation") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- #subset after  -->
<!-- Idents(gbm) <- "consensus_3celltypes_each" -->
<!-- gbm_filter_each <- subset(x = gbm, idents =c("AClike",  "OPClike", "NPClike")) -->
<!-- gbm_filter_each <- subset(x = gbm_filter_each, subset = confidence_3celltypes_each >= 0.5) -->

<!-- Idents(gbm) <- "consensus_3celltypes_whole" -->
<!-- gbm_filter_whole <- subset(x = gbm, idents =c("AClike",  "OPClike", "NPClike")) -->
<!-- gbm_filter_whole <- subset(x = gbm_filter_whole, subset = confidence_3celltypes_whole >= 0.5) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- DimPlot(gbm_filter_each,reduction = "umap",split.by = "consensus_3celltypes_each",group.by = "radiation") -->
<!-- DimPlot(gbm_filter_whole,reduction = "umap",split.by = "consensus_3celltypes_whole",group.by = "radiation") -->
<!-- ``` -->
<!-- ```{r} -->
<!-- #Do the analysis donor_wise -->
<!-- gbm.list <- SplitObject(gbm, split.by = "donor_id") -->

<!-- # gbm.list[["run2_radiated_E31N"]] <- merge(gbm.list[["run2_radiated_E31N"]], y=gbm.list[["run1_radiated_E31N"]]) -->
<!-- # gbm.list[["run2_control_E31N"]] <- merge(gbm.list[["run2_control_E31N"]], y=gbm.list[["run1_control_E31N"]]) -->
<!-- # gbm.list[["run2_radiated_E26N"]] <- merge(gbm.list[["run2_radiated_E26N"]], y=gbm.list[["run1_radiated_E26N"]]) -->
<!-- # gbm.list[["run2_radiated_E24N"]] <- merge(gbm.list[["run2_radiated_E24N"]], y=gbm.list[["run1_radiated_E24N"]]) -->
<!-- # gbm.list[c("run1_radiated_E24N","run1_radiated_E26N","run1_control_E31N","run1_radiated_E31N")] <- NULL -->

<!-- n.cores <- detectCores() -3 -->
<!-- #gbm.list <- mclapply(gbm.list,mc.cores = n.cores,function(x) { -->
<!-- gbm.list <- lapply(gbm.list,function(x) { -->
<!--   x <- NormalizeData(x) -->
<!--   x <- ScaleData(x) -->
<!--   x <- FindVariableFeatures(x) -->
<!--   x <- RunPCA(x) -->
<!--   x <- RunUMAP(x,dims = 1:20) -->
<!--   #x <- RunTSNE(x,dims = 1:20)  -->
<!-- }) -->

<!-- #Filtering out -->
<!-- #gbm.list.filtered <- mclapply(gbm.list,mc.cores = n.cores,function(x) { -->
<!-- gbm.list.filtered <- lapply(gbm.list,function(x) { -->
<!-- Idents(x) <- "consensus_3celltypes_each" -->
<!-- x <- subset(x = x, idents =c(""), invert = TRUE) -->
<!-- x <- subset(x = x, subset = confidence_3celltypes_each >= 0.5) -->
<!-- }) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- for (i in gbm.list.filtered) { -->
<!--   print(DimPlot(i,reduction = "umap",split.by = "consensus_3celltypes_each",group.by = "radiation")) -->
<!-- } -->
<!-- ``` -->
<!-- ```{r} -->
<!-- library(dplyr) -->
<!-- library(tibble) -->
<!-- library(metap) # for Fisher's method -->

<!-- # Find DE features between AC raidated and AC control -->
<!-- ac.de.markers.list <- lapply(gbm.list.filtered, function(x) { -->
<!--   x$consensus_radiation <- paste(x$consensus_3celltypes_each,x$radiation,sep = "_") -->
<!--   Idents(x) <- "consensus_radiation" -->
<!--   x <- FindMarkers(x, ident.1 = "AClike_radiated", ident.2 = "AClike_control") -->
<!-- }) -->



<!-- # Assuming list_of_dfs is your list of dataframes -->
<!-- significance_threshold <- 0.05 -->
<!-- consistency_threshold <- 0.5 # e.g., 70% replicates -->

<!-- # Combine all dataframes -->
<!-- combined_df <- bind_rows(lapply(ac.de.markers.list, rownames_to_column, var = "gene")) -->

<!-- # Find the minimum non-zero p-value in the combined dataframe -->
<!-- min_nonzero_p_val <- min(combined_df$p_val_adj[combined_df$p_val_adj > 0], na.rm = TRUE) -->

<!-- # Replace zero p-values with the minimum non-zero p-value -->
<!-- combined_df <- combined_df %>% -->
<!--                mutate(p_val_adj = ifelse(p_val_adj == 0, min_nonzero_p_val, p_val_adj)) -->

<!-- # Add a column to indicate the direction of change (upregulation or downregulation) -->
<!-- combined_df <- combined_df %>% -->
<!--                mutate(direction = ifelse(avg_log2FC > 0, "up", "down")) -->

<!-- # Filter for significant genes in the combined dataframe -->
<!-- filtered_combined_df <- filter(combined_df, p_val_adj < significance_threshold) -->

<!-- # Calculate the consistency of significance and direction across replicates for each gene -->
<!-- consistency_df <- filtered_combined_df %>% -->
<!--                   group_by(gene) %>% -->
<!--                   summarize(total_significant = n(), -->
<!--                             consistency_ratio = total_significant / length(ac.de.markers.list), -->
<!--                             consistent_direction = n_distinct(direction) == 1) %>% -->
<!--                   filter(consistency_ratio >= consistency_threshold, consistent_direction) -->

<!-- # Extract gene names of consistently significant genes with consistent direction -->
<!-- consistently_significant_genes <- consistency_df$gene -->

<!-- # Calculate combined p-value using Fisher's method for these genes -->
<!-- combined_pval_df <- filtered_combined_df %>% -->
<!--                     filter(gene %in% consistently_significant_genes) %>% -->
<!--                     group_by(gene) %>% -->
<!--                     summarize(combined_pval = sumlog(p_val_adj)$p) -->

<!-- # Merge consistency_df with combined_pval_df -->
<!-- final_summary_df <- inner_join(consistency_df, combined_pval_df, by = "gene") -->

<!-- # Sort the final summary dataframe first by consistency_ratio, then by combined_pval -->
<!-- final_summary_df <- final_summary_df %>% -->
<!--                     arrange(desc(consistency_ratio), combined_pval) -->

<!-- # Filter each original dataframe for consistently significant genes with consistent direction -->
<!-- final_filtered_dfs <- lapply(ac.de.markers.list, function(df) { -->
<!--     df <- rownames_to_column(df, var = "gene") -->
<!--     filter(df, gene %in% consistently_significant_genes) -->
<!-- }) -->

<!-- # Optionally, convert the 'gene' column back to rownames in final filtered dataframes -->
<!-- final_dfs <- lapply(final_filtered_dfs, function(df) { -->
<!--     column_to_rownames(df, var = "gene") -->
<!-- }) -->


<!-- ``` -->
<!-- ```{r} -->
<!-- library(dplyr) -->
<!-- library(tibble) -->
<!-- library(metap) # for Fisher's method -->

<!-- # Function to set consensus_radiation as Idents -->
<!-- set_consensus_radiation <- function(data_list) { -->
<!--   lapply(data_list, function(x) { -->
<!--     x$consensus_radiation <- paste(x$consensus_3celltypes_each, x$radiation, sep = "_") -->
<!--     Idents(x) <- "consensus_radiation" -->
<!--     return(x) -->
<!--   }) -->
<!-- } -->

<!-- # Function to perform DE analysis with error and warning handling -->
<!-- perform_DE_analysis <- function(x, cell_type_1) { -->
<!--   ident1 <- paste(cell_type_1, "radiated", sep = "_") -->
<!--   ident2 <- paste(cell_type_1, "control", sep = "_") -->

<!--   if (ident1 %in% levels(Idents(x)) && ident2 %in% levels(Idents(x))) { -->
<!--     tryCatch({ -->
<!--       FindMarkers(x, ident.1 = ident1, ident.2 = ident2) -->
<!--     }, error = function(e) { -->
<!--       warning(paste("Error in FindMarkers for:", cell_type_1, "\n", e)) -->
<!--       return(NULL) -->
<!--     }, warning = function(w) { -->
<!--       warning(paste("Warning in FindMarkers for:", cell_type_1, "\n", w)) -->
<!--       return(NULL) -->
<!--     }) -->
<!--   } else { -->
<!--     warning(paste("Identities not found in the object for:", cell_type_1)) -->
<!--     return(NULL) -->
<!--   } -->
<!-- } -->

<!-- # Function to process and combine DE results -->
<!-- process_DE_results <- function(de_list, significance_threshold, consistency_threshold) { -->
<!--   # Filter out NULLs or non-dataframe elements -->
<!--   valid_de_list <- Filter(function(df) is.data.frame(df), de_list) -->

<!--   # Combine all valid dataframes -->
<!--   combined_df <- bind_rows(lapply(valid_de_list, rownames_to_column, var = "gene")) -->

<!--   # Check if combined_df is empty -->
<!--   if (nrow(combined_df) == 0) { -->
<!--     warning("No valid dataframes for analysis") -->
<!--     return(NULL) -->
<!--   } -->

<!--   # Find the minimum non-zero p-value -->
<!--   min_nonzero_p_val <- min(combined_df$p_val_adj[combined_df$p_val_adj > 0], na.rm = TRUE) -->

<!--   # Process combined dataframe -->
<!--   combined_df %>% -->
<!--     mutate(p_val_adj = ifelse(p_val_adj == 0, min_nonzero_p_val, p_val_adj), -->
<!--            direction = ifelse(avg_log2FC > 0, "up", "down")) %>% -->
<!--     filter(p_val_adj < significance_threshold) %>% -->
<!--     group_by(gene) %>% -->
<!--     summarize(total_significant = n(), -->
<!--               consistency_ratio = total_significant / length(valid_de_list), -->
<!--               consistent_direction = n_distinct(direction) == 1, -->
<!--               combined_pval = sumlog(p_val_adj)$p) %>% -->
<!--     filter(consistency_ratio >= consistency_threshold, consistent_direction) %>% -->
<!--     arrange(desc(consistency_ratio), combined_pval) -->
<!-- } -->


<!-- # Preprocess data list and maintain names -->
<!-- gbm.list.filtered <- set_consensus_radiation(gbm.list.filtered) -->
<!-- names_gbm <- names(gbm.list.filtered) -->

<!-- # Apply the analysis for different cell types and maintain names -->
<!-- run_analysis_and_maintain_names <- function(cell_type) { -->
<!--   result_list <- lapply(gbm.list.filtered, perform_DE_analysis, cell_type_1 = cell_type) -->
<!--   names(result_list) <- names_gbm -->
<!--   return(result_list) -->
<!-- } -->



<!-- ac_de_markers_list <- run_analysis_and_maintain_names("AClike") -->
<!-- opc_de_markers_list <- run_analysis_and_maintain_names("OPClike") -->
<!-- npc_de_markers_list <- run_analysis_and_maintain_names("NPClike") -->

<!-- # Process and combine DE results -->
<!-- final_summary_ac <- process_DE_results(ac_de_markers_list, 0.05, 0.5) -->
<!-- opc_de_markers_list$E39N -->
<!-- final_summary_opc <- process_DE_results(opc_de_markers_list, 0.05, 0.5) -->
<!-- final_summary_npc <- process_DE_results(npc_de_markers_list, 0.05, 0.5) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- final_dfs -->
<!-- ``` -->





