---
title: "import"
output: html_document
date: '2023-06-05'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load all packages
```{r}
# load library
library(Seurat)
library(SeuratDisk)
library(ggplot2)
library(scCustomize)
library(DoubletFinder)
library(scales)
```


#Import into Seurat  
```{r}
# Load 10x in local
gbm.list <- list()
batch <- c()
for (n in 1:length(runs)) {
  for (m in 1:length(radiation)) {
    run <- runs[n]
    donor.group <- radiation[m]

    data.dir <- paste0("./../data/scRNA_", run, "/")

    mtx <- Read10X(data.dir = paste0(data.dir, "matrix_", donor.group, "_", run))
    gbm <- CreateSeuratObject(mtx, project = "glioblastoma", min.cells = 5, min.features = 200)



    # So there is no metadata of patient cell line yet >> add one from file name radiated_donor_ide.tsv (or control_donor_ide.tsv)
    gbm.donor.id <- read.table(file = paste0(data.dir, donor.group, "_donor_ids.tsv"), sep = "\t", header = TRUE, stringsAsFactors = TRUE)


    # check whether the metadata and donor_id sorted in same order
    table(rownames(gbm@meta.data) == gbm.donor.id$cell)
    # OK exact match


    # Then, add metadata into seurat object
    ## First make rowname for donor_id as it require for Addmetadata function
    rownames(gbm.donor.id) <- gbm.donor.id[, 1]
    gbm.donor.id <- gbm.donor.id[, -1]

    ## addmetadata
    gbm <- AddMetaData(gbm, gbm.donor.id["donor_id"])

    # Add label
    gbm$radiation <- donor.group
    gbm$orig.id <- rownames(gbm@meta.data)
    gbm$runs <- run
    gbm$batch <- paste0(gbm$runs, "_", gbm$radiation)
    gbm$split <- paste0(gbm$runs, "_", gbm$radiation, "_", gbm$donor_id)
    gbm$donor_run <- paste0(gbm$donor_id, "_", gbm$runs)
    gbm$donor_radiation <- paste0(gbm$donor_id, "_", gbm$radiation)


    # Change rownames to add experiment and runs so that merge clearly
    x <- paste0(gbm$runs, "_", gbm$radiation, "_", rownames(gbm@meta.data))
    gbm <- RenameCells(gbm, new.names = x)
    gbm <- list(gbm)
    gbm.list <- append(gbm.list, gbm)
    batch <- append(batch, paste0(runs[n], "_", radiation[m]))
  }
}
names(gbm.list) <- batch
```




```{r}
gbm <- Merge_Seurat_List(gbm.list)
```

```{r}
gbm@meta.data
```
```{r}
gbm.meta <- gbm@meta.data
gbm.meta <- gbm.meta[c("split", "donor_id", "batch", "radiation", "runs")]
gbm.meta
write.csv(gbm.meta, "./../output/gbm_meta.csv", row.names = TRUE)
```

#Check pooled unassigned and cross-doublet
```{r}
donor.per <- data.frame(prop.table(table(gbm[["split"]])))
ggplot(donor.per, aes(x = split, y = Freq)) +
  geom_bar(stat = "identity") +
  ggtitle("Percentage of cells from gbm group of each donor") +
  labs(y = "Percentage", subtitle = paste0("run1+2 ; control + radiated")) +
  theme(
    plot.title = element_text(hjust = 0.5, size = 15),
    axis.text.x = element_text(angle = 90, size = 4)
  )
```
```{r}
ggsave(paste0("donor_id_proportion"), path = "./../figure/", device = "png")
```

```{r}
# filter out
Idents(gbm) <- "donor_id"
gbm <- subset(gbm, idents = c("unassigned", "doublet"), invert = TRUE)
gbm@meta.data <- droplevels(gbm@meta.data)
```


#QC
```{r}
# filter by MT, Count, feature
gbm[["percent.mt"]] <- PercentageFeatureSet(gbm, pattern = "^MT-")
```

```{r}
Idents(gbm) <- "batch"
VlnPlot(gbm, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
plot2 <- FeatureScatter(gbm, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot3 <- FeatureScatter(gbm, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot2
plot3
```

```{r}
ggplot(gbm@meta.data, aes(x = batch, y = percent.mt)) +
  geom_violin(aes(fill = batch)) +
  scale_y_continuous(breaks = seq(0, 70, 10))
```

```{r}
ggplot(gbm@meta.data, aes(x = batch, y = nFeature_RNA)) +
  geom_violin(aes(fill = batch))
```
```{r}
ggplot(gbm@meta.data, aes(x = batch, y = nCount_RNA)) +
  geom_violin(aes(fill = batch))
```

```{r}
library(scales)
ggplot(gbm@meta.data, aes(x = nCount_RNA, y = percent.mt)) +
  geom_point(size = 0.2) +
  facet_wrap(~batch, ncol = 2) +
  theme(
    axis.text.x = element_text(
      size = 5, angle = 90
    ),
    axis.text.y = element_text(
      size = 6
    )
  ) +
  scale_y_continuous(breaks = seq(0, 100, 10)) +
  scale_x_continuous(breaks = c(10000, 50000, 100000, 200000)) +
  geom_hline(yintercept = 10, linetype = "dashed", color = "red") +
  geom_vline(xintercept = 10000, linetype = "dashed", color = "red") +
  geom_vline(xintercept = 100000, linetype = "dashed", color = "red") +
  labs(title = "batch")
```


```{r}
gbm <- subset(
  gbm,
  percent.mt < 20
)

# if as Lucy
# gbm <- subset(gbm, subset = nCount_RNA > 10000 & percent.mt < 10)
```

```{r}
# Add nCell_RNA
ncell <- rowSums(gbm@assays$RNA@counts != 0)
gbm[["RNA"]] <- AddMetaData(gbm[["RNA"]], metadata = ncell, col.name = "nCell_RNA")
```

```{r}
saveRDS(gbm, paste0("./../output/", "seurat_gbm_qc"), compress = TRUE)
    ```

```{r}
gbm <- CellCycleScoring(
  object = gbm, g2m.features = cc.genes$g2m.genes,
  s.features = cc.genes$s.genes
)
```
```{r}
VlnPlot(gbm,
  features = c("S.Score", "G2M.Score"), group.by = "orig.ident",
  ncol = 4, pt.size = 0.1
)
```

```{r}
gbm <- NormalizeData(gbm, verbose = FALSE)
gbm <- FindVariableFeatures(gbm, verbose = F)
gbm <- ScaleData(gbm,
  vars.to.regress = c("nFeature_RNA", "percent.mt"),
  verbose = F
)
gbm <- RunPCA(gbm, verbose = F, npcs = 20)
gbm <- RunUMAP(gbm, dims = 1:10, verbose = F)
```






```{r}
gbm@meta.data
```

# Trying filter nCount, nFeature the similar way as Neftel
```{r}
gbm.list <- SplitObject(gbm, split.by = "batch")

gbm.list <- lapply(X = gbm.list, FUN = function(x) {
  mean.count <- mean(x$nCount_RNA)
  x <- subset(x, subset = nCount_RNA > (0.5 * mean.count) & nCount_RNA < (2 * mean.count) & percent.mt < 10)
})
```

```{r}
quantile(gbm$nCount_RNA)
```

```{r}
gbm.filtered <- Merge_Seurat_List(gbm.list)
```

```{r}
ggplot(gbm.filtered@meta.data, aes(x = nCount_RNA, y = percent.mt)) +
  geom_point(size = 0.2) +
  facet_wrap(~batch, ncol = 2) +
  theme(
    axis.text.x = element_text(
      size = 5, angle = 90
    ),
    axis.text.y = element_text(
      size = 6
    )
  ) +
  scale_y_continuous(breaks = seq(0, 100, 10)) +
  scale_x_continuous(breaks = c(10000, 50000, 100000, 200000)) +
  geom_hline(yintercept = 10, linetype = "dashed", color = "red") +
  geom_vline(xintercept = 10000, linetype = "dashed", color = "red") +
  geom_vline(xintercept = 100000, linetype = "dashed", color = "red") +
  labs(title = "batch")
```
```{r}
table(gbm.filtered$split)
```


#Try SCE
```{r}
library(SingleCellExperiment)

gbm <- readRDS("./../output/seurat_gbm_qc")
gbm <- NormalizeData(gbm)
gbm.sce <- as.SingleCellExperiment(gbm)
```



```{r}
# import smartseq
smrt_mtx <- read.delim("./../data/neftel/IDHwtGBM.processed.SS2.logTPM.txt.gz")
rownames(smrt_mtx) <- smrt_mtx[, 1]
smrt_mtx <- smrt_mtx[, -1]
head(smrt_mtx)
colnames(smrt_mtx) <- gsub("\\.", "-", colnames(smrt_mtx))
smrt_mtx <- smrt_mtx[, order(colnames(smrt_mtx))]
head(smrt_mtx)

meta <- read.delim("./../data/neftel/metadata.txt")
meta <- meta[-1, ]
rownames(meta) <- meta$NAME
meta <- meta[order(rownames(meta)), ]

# library(Seurat)
# smrt <- CreateSeuratObject(smrt_mtx,meta.data = meta)
#
# rm(smrt_mtx)

smrt_mtx[1:3, 1:4]
head(meta)
```


```{r}
neftel.smrt <- SingleCellExperiment(
  assays = list(logcounts = as.matrix(smrt_mtx)),
  colData = meta
)
```

```{r}
class(meta)
neftel.smrt
as.data.frame(colData(neftel.smrt))
```


