#calculation -->
<!-- ```{r} -->
<!-- library(data.table) -->
<!-- library(Seurat) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- gbm <- readRDS("output/seurat_gbm_qc") -->

<!-- p12 <- fread("data/pi12.csv") -->
<!-- p12 <- p12[,.(Genes,`Coefficients of Lasso-Cox Model`)] -->
<!-- setnames(p12,"Coefficients of Lasso-Cox Model","Coefficients_of_Lasso_Cox_Model") -->
<!-- p12[,Coefficients_of_Lasso_Cox_Model := as.numeric(Coefficients_of_Lasso_Cox_Model)] -->
<!-- p12 <- p12[!Coefficients_of_Lasso_Cox_Model == 0,] -->
<!-- ``` -->


<!-- ```{r} -->
<!-- ggVennDiagram::ggVennDiagram(x= list(post_processed = rownames(gbm), -->
<!--                                      p12 = p12$Genes)) -->
<!-- setdiff(p12$Genes,rownames(gbm)) -->

<!-- #so one gene is missing. I check and it was filtered from preprocessing process -->
<!-- ``` -->

<!-- ```{r} -->
<!-- common_gene <- intersect(p12$Genes,rownames(gbm)) -->
<!-- p11 <- p12[Genes %in% common_gene] -->
<!-- p12 -->
<!-- p11 -->
<!-- ``` -->
<!-- ```{r} -->
<!-- gc() -->
<!-- ``` -->

<!-- ```{r} -->
<!-- gbm <- NormalizeData(gbm) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- #gbm[["RNA"]]$data -->
<!-- gem.lognorm.p11 <- (gbm[["RNA"]]$data)[rownames(gbm[["RNA"]]$data) %in% p11$Genes,] -->
<!-- dim(gem.lognorm.p11) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- p11 <- p11[order(p11$Genes),] -->
<!-- gem.lognorm.p11 <- gem.lognorm.p11[p11$Genes,] -->

<!-- ``` -->


<!-- ```{r} -->
<!-- gem.lognorm.p11_score <- gem.lognorm.p11 * p11$Coefficients_of_Lasso_Cox_Model -->
<!-- gem.lognorm.p11_score <- colSums(gem.lognorm.p11_score) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- gbm <- NormalizeData(gbm,normalization.method = "RC") -->
<!-- ``` -->
<!-- ```{r} -->
<!-- #gbm[["RNA"]]$data -->
<!-- gem.norm.p11 <- (gbm[["RNA"]]$data)[rownames(gbm[["RNA"]]$data) %in% p11$Genes,] -->
<!-- dim(gem.norm.p11) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- p11 <- p11[order(p11$Genes),] -->
<!-- gem.norm.p11 <- gem.norm.p11[p11$Genes,] -->
<!-- p11$Genes == rownames(gem.norm.p11) -->


<!-- (p11$Coefficients_of_Lasso_Cox_Model) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- gem.norm.p11_score <- gem.norm.p11 * p11$Coefficients_of_Lasso_Cox_Model -->
<!-- gem.norm.p11_score <- colSums(gem.norm.p11_score) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- p11_score_df <- data.frame(cell_id = names(gem.p11_score), -->
<!--                            p11_rc_score = gem.norm.p11_score, -->
<!--                            p11_lognorm_score = gem.lognorm.p11_score) -->
<!-- fwrite(p11_score_df,"output/annotation/p11_score.csv",row.names = FALSE) -->
<!-- ``` -->

#compare RSI to P11
```{r}
library(data.table)
library(ggplot2)
library(dplyr)
```


```{r}
rsi <- fread("output/annotation/sen_RSI_cellstate.csv")
p11 <- fread("output/annotation/p11_score.csv")

p11
```

```{r}
setnames(rsi,"cell_id_Yossawat","cell_id")
```

```{r}
p11_rsi <- merge(rsi,p11,by = "cell_id")
p11_rsi
```


```{r}
p11_rsi <- p11_rsi[,.(cell_id,donor_id,radiation,runs,RSI,p11_rc_score,p11_lognorm_score)]
p11_rsi
```


```{r}
hist(p11_rsi$RSI)
hist(p11_rsi$p11_rc_score)
hist(p11_rsi$p11_lognorm_score)
```
```{r}
p11_rsi %>% ggplot(aes(y=p11_rc_score,x=radiation)) + geom_violin() + facet_wrap(~donor_id)
p11_rsi %>% ggplot(aes(y=p11_rc_score,x=radiation)) + geom_boxplot() + facet_wrap(~donor_id)
```

```{r}

p11_rsi %>% ggplot(aes(y=p11_lognorm_score,x=radiation)) + geom_violin() + facet_wrap(~donor_id)
p11_rsi %>% ggplot(aes(y=p11_lognorm_score,x=radiation)) + geom_boxplot() + facet_wrap(~donor_id)
```
```{r}
p11_rsi %>% ggplot(aes(y=RSI,x=radiation)) + geom_violin() + facet_wrap(~donor_id)
p11_rsi %>% ggplot(aes(y=RSI,x=radiation)) + geom_boxplot() + facet_wrap(~donor_id)
```

