



---
title: "All"
output: html_document
date: '2023-06-08'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r}
#Set working directory
library(here)
setwd(here())
```

```{r}
# install.packages(c("SCINA","scSorter"))
# install.packages("BiocManager")
# BiocManager::install("preprocessCore",force = TRUE)
install.packages("writexl")
```

```{r}
library(ggplot2)
library(Seurat)
library(dplyr)
library(readxl)
library(tibble)
library(patchwork)
library(parallel)
library(purrr)
library(tibble)
library(writexl)

source("script/function.R")
```


```{r}
# Parameter
# Select the signature to be used
# if it is new one, can add into the list but keep in mind to run the preprocessing of the signatures in the next chunk because it need to be preprocessed into xlsx file first
sigs <- c( "4metamodules_new_50_mes",
           "2metamodules_NPC_OPC", 
           "3metamodules_new_50",
           "4metamodules_new_50",
           "npcopc_ac_mes",
           "npcopc_acmes",
           "4pathways",
           "neurodev_bulk",
           "vc_common")
run_eachs <- c(TRUE,FALSE)
runs <- c("each","whole")
#signatures.gen <- c("signature_new","signature_bulk")

```



```{r}
sig <- sigs[7]
sig

# cell input to be analyse

object <- "all"


run_each <- run_eachs[1]

if (run_each) {
  run <- runs[1]
} else {
  run <- runs[2]
}
```


#signature preprocessing
```{r}

# automatic convert gene list
signatures <- read.csv(paste0("output/signature/signature_subtype_", sig, ".csv"))

# scsorter
signatures.split <- list()
for (i in 1:ncol(signatures)) {
  signatures.each <- na.omit(signatures[i])
  signatures.split <- append(signatures.split, list(signatures.each))
}

signatures.split <- lapply(signatures.split, FUN = function(x) {
  x <- cbind(rep(colnames(x), nrow(x)), x)
  colnames(x) <- c("Type", "Marker")
  return(x)
})

signatures.scsorter <- do.call(rbind, signatures.split)

# sctype
signatures.merge <- apply(signatures, 2, paste0, collapse = ",")

signatures.sctype <- data.frame(signatures.merge)
colnames(signatures.sctype) <- "geneSymbolmore1"
signatures.sctype$geneSymbolmore2 <- NA
signatures.sctype <- rownames_to_column(signatures.sctype, var = "cellName")
tissueType <- data.frame(tissueType = rep("gbm", nrow(signatures.sctype)))

signatures.sctype <- cbind(tissueType, signatures.sctype)

# scID
signatures.split <- list()
for (i in 1:ncol(signatures)) {
  signatures.each <- na.omit(signatures[i])
  signatures.split <- append(signatures.split, list(signatures.each))
}

signatures.split <- lapply(signatures.split, FUN = function(x) {
  x <- cbind(rep(colnames(x), nrow(x)), x)
  colnames(x) <- c("cluster", "gene")
  return(x)
})

signatures.scid <- do.call(rbind, signatures.split)
signatures.scid$cluster <- as.factor(signatures.scid$cluster)


# SCINA
signatures.scina <- as.data.frame(signatures)
signatures.scina[is.na.data.frame(signatures.scina)] <- ""

# markercount
signatures.split <- list()
for (i in 1:ncol(signatures)) {
  signatures.each <- cbind(signatures[i], rep(1, nrow(signatures)))
  signatures.split <- append(signatures.split, list(signatures.each))
}

signatures.split <- lapply(signatures.split, FUN = function(x) {
  x <- data.frame(t(na.omit(x)))
  colnames(x) <- x[1, ]
  x[1, ] <- 1
  x <- x[1, ]
  x <- rownames_to_column(x, var = "celltype")
})

sig.markercount <- signatures.split %>% reduce(full_join, by = "celltype")
sig.markercount <- sig.markercount %>% column_to_rownames(var = "celltype")

# Save to xlsx to be used later
write_xlsx(signatures.sctype, path = paste0("data/gbm_", sig, "_sctype.xlsx"))
write_xlsx(signatures.scsorter, path = paste0("data/gbm_", sig, "_scsorter.xlsx"))

sig.markercount <- rownames_to_column(sig.markercount, var = "celltype")
write_xlsx(sig.markercount, path = paste0("data/gbm_", sig, "_markercount.xlsx"))

write_xlsx(signatures.scid, path = paste0("data/gbm_", sig, "_scID.xlsx"))
```



# load gbm
```{r}

gbm <- readRDS("output/seurat_objects/seurat_gbm_qc")

if (run_each) {
  gbm.list.original <- SplitObject(gbm, split.by = "split")

  gbm.list.original[["run2_radiated_E31N"]] <- merge(gbm.list.original[["run2_radiated_E31N"]], y=gbm.list.original[["run1_radiated_E31N"]])
  gbm.list.original[["run2_control_E31N"]] <- merge(gbm.list.original[["run2_control_E31N"]], y=gbm.list.original[["run1_control_E31N"]])
  gbm.list.original[["run2_radiated_E26N"]] <- merge(gbm.list.original[["run2_radiated_E26N"]], y=gbm.list.original[["run1_radiated_E26N"]])
  gbm.list.original[["run2_radiated_E24N"]] <- merge(gbm.list.original[["run2_radiated_E24N"]], y=gbm.list.original[["run1_radiated_E24N"]])
  gbm.list.original[c("run1_radiated_E24N","run1_radiated_E26N","run1_control_E31N","run1_radiated_E31N")] <- NULL
} else {
  gbm.list.original <- list(all = gbm)
}

rm(gbm)

```







##tools
#Sc-type
```{r}
#install.packages("HGNChelper")
#install.packages("openxlsx")

library(HGNChelper)

# Sctype
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/gene_sets_prepare.R")
source("https://raw.githubusercontent.com/IanevskiAleksandr/sc-type/master/R/sctype_score_.R")
```


```{r}
# Load genelist

# DB file
db_ <- paste0("data/gbm_", sig, "_sctype.xlsx")
as.list(signatures.sctype$geneSymbolmore1)
tissue <- "gbm"

# prepare gene sets
gs_list <- gene_sets_prepare(db_, tissue)
```

```{r}
gbm.list <- gbm.list.original
```

```{r}
features <- do.call(paste, args = as.list(signatures.sctype$geneSymbolmore1))
features <- gsub(" ", ",", features)
features <- strsplit(features, ",")
features <- unlist(features)

score.list <- list()
n.cores <- parallel::detectCores() - 5
# gbm.list.res <- lapply(X = gbm.list, FUN = function(x)  {
gbm.list <- mclapply(X = gbm.list, mc.cores = n.cores, FUN = function(x) {
  x <- NormalizeData(x, verbose = FALSE)
  x <- FindVariableFeatures(x, verbose = FALSE)

  x <- ScaleData(x, verbose = FALSE, features = rownames(x))

  x <- RunPCA(x, verbose = FALSE, features = features, npcs = 20)
  x <- FindNeighbors(x, reduction = "pca", dims = 1:20, verbose = FALSE)
  x <- FindClusters(x, verbose = FALSE,resolution = 1.2)
})
```





```{r}
# we use sctype_score_edited (just edit code to prevent matrix becoming vector) &rowSum part (both I add drop = FALSE) to prevent error when there is only on marker type
# gbm.list.res <- lapply(X = gbm.list[1],  FUN = function(x)  {
#gbm.list.res <- mclapply(X = gbm.list, mc.cores = n.cores, FUN = function(x) {
gbm.list.res <- mclapply(X = gbm.list, mc.cores = 3, FUN = function(x) {  
  es.max <- sctype_score_edited(
    scRNAseqData = x[["RNA"]]@scale.data, scaled = TRUE,
    gs = gs_list$gs_positive, gs2 = NULL
  )

  cL_resutls <- do.call("rbind", lapply(unique(x@meta.data$seurat_clusters), function(cl) {
    es.max.cl <- sort(rowSums(es.max[, rownames(x@meta.data[x@meta.data$seurat_clusters == cl, ]), drop = FALSE]), decreasing = !0)
    head(data.frame(cluster = cl, type = names(es.max.cl), scores = es.max.cl, ncells = sum(x@meta.data$seurat_clusters == cl)), 10)
  }))
  sctype_scores <- cL_resutls %>%
    group_by(cluster) %>%
    top_n(n = 1, wt = scores)
  
  sctype_scores$type_no_unknown <- sctype_scores$type
  sctype_scores$type[as.numeric(as.character(sctype_scores$scores)) < sctype_scores$ncells/4] <- "Unknown"


  #score.list <- append(score.list, sctype_scores)
  x@meta.data$scType <- ""
  x@meta.data$scType_no_unknown <- ""
  for (j in unique(sctype_scores$cluster)) {
    cl_type <- sctype_scores[sctype_scores$cluster == j, ]
    x@meta.data$scType[x@meta.data$seurat_clusters == j] <- as.character(cl_type$type[1])
    x@meta.data$scType_no_unknown[x@meta.data$seurat_clusters == j] <- as.character(cl_type$type_no_unknown[1])
    
  }
  return(x)
})
```

```{r}
each.meta.all <- data.frame(matrix(nrow = 0,ncol = 2))
for (i in gbm.list.res) {
  each.meta <- i@meta.data[,c("scType","scType_no_unknown")]
  each.meta.all <- rbind(each.meta.all, each.meta)
}
```



```{r}
write.csv(each.meta.all, paste0("output/annotation_result_each_tool/scType_", object, "_", sig,"_",run, ".csv"), row.names = TRUE)
```

```{r}
unloadNamespace("HGNChelper")
rm(each.meta.all,features,db_,tissue,gs_list,score.list,gbm.list.res,i)
gc()
```




#SCINA
```{r}
library(SCINA)

#BiocManager::install("preprocessCore")
library(preprocessCore)

#marker based
#normalized by quantile + log1p
#Expectation-maximization inference
```


```{r}
gbm.list <- gbm.list.original
```






```{r}
gbm.list.res <- mclapply(gbm.list,mc.cores = 2, FUN = function(x){
# gbm.list.res <- lapply(gbm.list,FUN = function(x){ 
# x <- gbm.list[[1]]
  exp <- log(x@assays$RNA@counts + 1) # log norm 
  exp[] = normalize.quantiles(as.matrix(exp)) # if it error this step, follow this https://github.com/Bioconductor/bioconductor_docker/issues/22 . Also instill it within rstudio
  results = SCINA(exp, signatures.scina, rm_overlap=FALSE, allow_unknown=TRUE)
  return(results)
})
```

```{r}
# 
```

```{r}
names(gbm.list.res) <- names(gbm.list)
```




```{r}
res.df <- data.frame()
for (i in gbm.list.res) {
  cell_labels <- data.frame(SCINA = i$cell_labels,stringsAsFactors = TRUE)
  rownames(cell_labels) <- colnames(i$probabilities)
  probs <- i$probabilities[,which(cell_labels$SCINA == "unknown"),drop = FALSE]
  rownames(probs)[apply(probs, 2, which.max)]
  cell_labels$SCINA_no_unknown <- cell_labels$SCINA
  cell_labels[cell_labels$SCINA == "unknown","SCINA_no_unknown"] <- rownames(probs)[apply(probs, 2, which.max)]
  res.df <- rbind(res.df, cell_labels)
}
```




```{r}
write.csv(res.df,paste0("output/annotation_result_each_tool/SCINA_",object,"_",sig,"_",run,".csv"),row.names = TRUE)
```

```{r}
unloadNamespace("SCINA")
rm(res.df,cell_labels,gbm.list.res)
gc()
```

#scSorter -->
```{r}
#library(scSorter)
library(scSorterEdited)
#Load annotation

anno <- as.data.frame(read_xlsx(paste0("data/gbm_",sig,"_scsorter.xlsx")))

# make sure that anno is dataframe not the tibble bc it wil cause problem in rts function later if it is tibble
```

```{r}
gbm.list <- gbm.list.original
```


```{r}

#n.cores <- parallel::detectCores() - 1
n.cores <- 2

system.time(gbm.list <- mclapply(X = gbm.list, mc.cores = n.cores, FUN = function(x)  {

  x <- NormalizeData(x,verbose = FALSE)
  x <- FindVariableFeatures(x,verbose = FALSE)


}))
```


```{r}
#system.time(gbm.list.res <- mclapply(X = gbm.list, mc.cores = n.cores, FUN = function(x)  {
system.time(gbm.list.res <- lapply(X = gbm.list[1], FUN = function(x)  {

  #x <- gbm.list[[1]]
  topgenes <- head(VariableFeatures(x), 2000)
  # gene expression need to be library normalized and log tranform first! #
  expr = GetAssayData(x, assay = "RNA", layer = "data")
  topgene_filter = rowSums(as.matrix(expr)[topgenes, ]!=0) > ncol(expr)*.1
  topgenes = topgenes[topgene_filter]
  picked_genes = unique(c(anno$Marker, topgenes))
  expr = expr[rownames(expr) %in% picked_genes, ]
  

  rts <- scSorter(expr, anno)
  
  #rts <- scSorter_edited(expr, anno)
  
  x <- AddMetaData(x,rts$Pred_Type, col.name = "scSorter")
  each.meta <- x@meta.data[c("scSorter")]
  each.meta <- rownames_to_column(each.meta)

  return(list(rts=rts,each.meta=each.meta))
}))
```

#explore scSorter function -->
<!-- ```{r} -->
<!-- scSorter_edited <- function(expr, anno, default_weight = 2, n_start = 10, alpha = 0, u = 0.05, max_iter = 100, setseed = 0){ -->
<!--   #this is a wrapper function that implements the whole method based on the rest functions. -->
<!--   #Rfast package is needed to run this method. -->
<!--   anno_processed = design_matrix_builder_edited(anno, default_weight) -->
<!--   dt = data_preprocess_edited(expr, anno_processed) -->

<!--   dat = dt[[1]] -->
<!--   designmat = dt[[2]] -->
<!--   weightmat = dt[[3]] -->

<!--   c_cost = NULL -->
<!--   c_mu = list() -->
<!--   c_clus = list() -->

<!--   for(i in 1:n_start){ -->
<!--     set.seed(i+setseed) -->
<!--     t1 = Sys.time() -->
<!--     pred_ot = update_func(as.matrix(dat), designmat, weightmat, unknown_threshold1 = alpha, unknown_threshold2 = u, max_iter = max_iter) -->
<!--     t2 = Sys.time() -->

<!--     c_cost = c(c_cost, pred_ot[[3]]) -->
<!--     c_mu[[i]] = pred_ot[[1]] -->
<!--     c_clus[[i]] = pred_ot[[2]] -->
<!--   } -->

<!--   pk = which.min(c_cost) -->

<!--   pred_clus = c_clus[[pk]] -->
<!--   pred_clus = c(colnames(designmat), rep('Unknown', ncol(designmat)))[pred_clus] -->
<!--   pred_mu = c_mu[[pk]] -->

<!--   return(list(Pred_Type = pred_clus, Pred_param = pred_mu)) -->
<!-- } -->


<!-- design_matrix_builder_edited <- function(anno, weight){ -->
<!--   if(weight <= 0)stop(paste('Default weight should be positive instead of the assigned value of ', weight, '.', sep = '')) -->

<!--   colnames(anno) = toupper(colnames(anno)) -->

<!--   if(sum(c('TYPE', 'MARKER') %in% colnames(anno)) == 2) { -->
<!--     ror = c(which(colnames(anno) == 'TYPE'), which(colnames(anno) == 'MARKER')) -->
<!--     lidx = c(1:ncol(anno))[!(1:ncol(anno) %in% ror)] -->
<!--     ror = c(ror, lidx) -->
<!--     anno = anno[, ror] -->
<!--   } -->

<!--   celltypes = unique(anno[,1]) -->
<!--   marker = unique(anno[,2]) -->

<!--   nc = length(celltypes) -->
<!--   nm = length(marker) -->

<!--   designmat = matrix(0, nm, nc) -->

<!--   nc_anno = ncol(anno) -->

<!--   if (nc_anno == 3) { -->
<!--     anno[, 3] = as.numeric(anno[, 3]) -->
<!--     poscheck = (anno[, 3] <= 0) -->
<!--     if(sum(poscheck) > 0) { -->
<!--       stop(paste('Please assign positive weights for the following marker genes: \n', -->
<!--                  paste(sapply(1:nrow(anno), function(x)paste(anno[x, 1], anno[x, 2], sep = ': '))[poscheck], collapse = ', \n'), -->
<!--                  '.', sep = '')) -->
<!--     } -->
<!--     weight = min(anno[, 3]) -->
<!--   } -->

<!--   weightmat = matrix(weight, nm, nc) -->

<!--   for (i in 1:nrow(anno)) { -->
<!--     designmat[which(marker == anno[i, 2]), which(celltypes == anno[i, 1])] = 1 -->
<!--     if (nc_anno == 3) weightmat[which(marker == anno[i, 2]), which(celltypes == anno[i, 1])] = anno[i, 3] -->
<!--   } -->

<!--   designmat = as.data.frame(designmat, stringsAsFactors = F) -->
<!--   colnames(designmat) = celltypes -->
<!--   rownames(designmat) = marker -->

<!--   colnames(weightmat) = celltypes -->
<!--   rownames(weightmat) = marker -->

<!--   return(list(designmat, weightmat)) -->
<!-- } -->

<!-- data_preprocess_edited = function(expr, anno_processed) { -->
<!--   designmat = anno_processed[[1]] -->
<!--   weightmat = anno_processed[[2]] -->

<!--   rownames(expr) = toupper(rownames(expr)) -->
<!--   rownames(designmat) = toupper(rownames(designmat)) -->

<!--   markers = rownames(designmat) -->

<!--   markers_avail = markers %in% rownames(expr) -->

<!--   if (sum(markers_avail) < length(markers)) { -->
<!--     warning(paste('The following specified marker genes are not found from the expression data: ', -->
<!--                   paste(markers[!markers_avail], collapse = ', '), '.', sep = '')) -->

<!--     designmat = designmat[markers_avail, ,drop =FALSE] -->
<!--     csdmat = colSums(designmat) -->

<!--     if(sum(csdmat > 0) < ncol(designmat)) { -->
<!--       stop(paste('None of the marker genes specfied for the following cell types could be found from the expression data: ', -->
<!--                     paste(colnames(designmat)[csdmat == 0], collapse = ', '), '. \n Please maker sure the marker gene names are correctly specified.', sep = '')) -->
<!--     } -->
<!--   } -->

<!--   dmat_gene_names = rownames(designmat) -->
<!--   dat_gene_names = rownames(expr) -->

<!--   picker = dat_gene_names %in% dmat_gene_names -->

<!--   expr_mk = expr[picker, ] -->
<!--   expr_rt = expr[!picker,] -->

<!--   #reorder genes so that the order of expr mat and design mat matches -->
<!--   ror = rep(0, nrow(designmat)) -->
<!--   for(i in 1:nrow(designmat)){ -->
<!--     ror[i] = which(rownames(expr_mk) == dmat_gene_names[i]) -->
<!--   } -->
<!--   expr_mk = expr_mk[ror,] -->

<!--   expr_cb = rbind(expr_mk, expr_rt) -->

<!--   return(list(dat = expr_cb, designmat = designmat, weightmat = weightmat)) -->
<!-- } -->

<!-- update_func_edited = function(dat, design_mat, weightmat, unknown_threshold1 = 0, unknown_threshold2 = 0.05, max_iter = 100){ -->
<!--   cluster = sample(1:ncol(design_mat), ncol(dat), replace = T) -->

<!--   rgwmat = range(weightmat) -->
<!--   if (rgwmat[1] == rgwmat[2]) { -->

<!--     ldt = nrow(dat) -->
<!--     lmk = nrow(design_mat) -->
<!--     marker_w = rep(weightmat[1, 1], lmk) -->
<!--     rest_w = rep(min(lmk/(ldt-lmk),1), ldt-lmk) -->
<!--     w = c(marker_w, rest_w) -->
<!--     dat = dat*sqrt(w) -->

<!--     for(i in 1:max_iter){ -->
<!--       mu = update_mu(dat, design_mat, cluster) -->
<!--       cluster_old = cluster -->
<!--       cluster_ot = update_C(dat, mu, design_mat) -->
<!--       cluster = cluster_ot[[1]] -->
<!--       if(sum(cluster != cluster_old)==0){ -->
<!--         break -->
<!--       } -->
<!--     } -->
<!--   } else { -->
<!--     ldt = nrow(dat) -->
<!--     lmk = nrow(design_mat) -->
<!--     rest_w = rep(min(lmk/(ldt-lmk),1), ldt-lmk) -->

<!--     dat_mk = dat[1:lmk, ] -->
<!--     dat_rt = dat[(lmk+1):ldt, ] -->

<!--     dat_rt = dat_rt * sqrt(rest_w) -->

<!--     weight_decorator = function(dat_mk, weightmat, clus) { -->
<!--       uniclus = unique(clus) -->
<!--       dat_mk2 = dat_mk -->

<!--       for (i in uniclus) { -->
<!--         marker_w = weightmat[, i] -->
<!--         dat_mk2[, clus == i] = dat_mk[, clus == i]*sqrt(marker_w) -->
<!--       } -->
<!--       return(dat_mk2) -->
<!--     } -->

<!--     for(i in 1:max_iter){ -->
<!--       dat2 = rbind(weight_decorator(dat_mk, weightmat, cluster), dat_rt) -->
<!--       mu = update_mu(dat2, design_mat, cluster) -->
<!--       cluster_old = cluster -->
<!--       cluster_ot = update_C(dat2, mu, design_mat) -->
<!--       cluster = cluster_ot[[1]] -->
<!--       if(sum(cluster != cluster_old)==0){ -->
<!--         break -->
<!--       } -->
<!--     } -->

<!--     dat = dat2 -->
<!--   } -->

<!--   cache_mat = cluster_ot[[2]] -->
<!--   numofmarkergenes = colSums(design_mat) -->
<!--   numofhighexpmkgenes = sapply(1:nrow(cache_mat), function(x)cache_mat[x,cluster[x]]/numofmarkergenes[cluster[x]]) -->
<!--   pks = numofhighexpmkgenes <= unknown_threshold1 -->

<!--   cluster_ukn_helper = cluster[pks] -->
<!--   cluster_ukn = cluster[pks] -->

<!--   cluster_kn = cluster[!pks] -->

<!--   dat_kn_add = dat[(lmk+1):ldt, !pks] -->
<!--   dat_ukn_add = dat[(lmk+1):ldt, pks, drop = F] -->

<!--   #detect unknown cells from a given cluster. -->
<!--   #Now we need to determine whether to put those potential unknown cells back to the corresponding cluster. -->
<!--   #The total cost of two groups of cells (cells of that cluster and unknown cells) should reach a minimum when true unknown cells are picked out while the rest are put back into the cluster. -->
<!--   #Under chi-square distribution, a cutoff is set to pick out true unknown cells. Since unknown cells are expected to be far away from the samples of that cluster. The search starts from one standard deviation. -->
<!--   #50 cutoffs are selected and the one leads to the minimum total cost are used as final cutoff. -->
<!--   unknown_detector = function(dat_kn, dat_ukn){ -->
<!--     pknz = rowSums(dat_kn != 0) != 0 -->
<!--     df = sum(pknz) -->

<!--     dat_kn = dat_kn[pknz,] -->
<!--     dat_ukn = dat_ukn[pknz,] -->

<!--     rm = rowMeans(dat_kn) -->
<!--     sdr = apply(dat_kn, 1, sd) -->

<!--     dat_kn2 = (dat_kn-rm)/sdr -->
<!--     dat_ukn2 = (dat_ukn-rm)/sdr -->

<!--     dsdat = colSums(dat_kn2^2) -->
<!--     dsdatuk = colSums(dat_ukn2^2) -->

<!--     cost_calc2 = function(x){ -->
<!--       mx = rowMeans(x) -->
<!--       return(sum((x-mx)^2)) -->
<!--     } -->

<!--     calc_target2 = function(p){ -->
<!--       pk = pchisq(dsdatuk,df) <= p -->
<!--       return(cost_calc2(cbind(dat_kn, dat_ukn[,pk]))+cost_calc2(dat_ukn[,!pk, drop = F])) -->
<!--     } -->

<!--     pl = c(seq(pchisq(df+sqrt(2*df),df),0.9,length.out = 10),seq(0.9, 0.95, length.out = 11)[2:11], seq(0.95, 0.99, length.out = 11)[2:11], seq(0.99, 1,length.out = 21)[2:21]) -->
<!--     ot = sapply(pl, calc_target2) -->

<!--     pl_chosen = pl[which.min(ot)[1]] -->

<!--     pkfinal = pchisq(dsdatuk, df) <= pl_chosen -->
<!--     return(pkfinal) -->
<!--   } -->

<!--   uni_clus_ukn = unique(cluster_ukn_helper) -->

<!--   nc = ncol(design_mat) -->

<!--   for(ucukn in uni_clus_ukn){ -->
<!--     #this part could be further modified to account for bad quality clusters -->
<!--     if(sum(cluster_kn==ucukn) <= max(1, round(unknown_threshold2*(sum(cluster_kn==ucukn)+sum(cluster_ukn_helper==ucukn))))){ -->
<!--       cluster_ukn[cluster_ukn_helper==ucukn] = nc+ucukn -->
<!--     }else if(sum(cluster_ukn_helper==ucukn)==1){ -->
<!--       cluster_ukn[cluster_ukn_helper==ucukn] = nc+ucukn -->
<!--     }else{ -->
<!--       uknrt = unknown_detector(dat_kn_add[,cluster_kn == ucukn], dat_ukn_add[,cluster_ukn_helper == ucukn, drop = F]) -->
<!--       cluster_ukn[cluster_ukn_helper==ucukn][!uknrt] = nc+ucukn -->
<!--     } -->
<!--   } -->

<!--   cluster[pks] = cluster_ukn -->

<!--   uniclus = unique(cluster) -->

<!--   for(allclus in 1:max(uniclus)){ -->
<!--     if(allclus>nc){ -->
<!--       design_mat[, paste('Unknown_', allclus-nc, sep = '')] = 0 -->
<!--       if(allclus %in% uniclus){ -->
<!--         mu = cbind(mu, c(rep(0, lmk), rowMeans(dat_ukn_add[, cluster_ukn == allclus, drop = F]))) -->
<!--       }else{ -->
<!--         mu = cbind(mu, rep(0, nrow(mu))) -->
<!--       } -->
<!--     }else{ -->
<!--       if(allclus %in% uniclus){ -->
<!--         mu[(lmk+1):ldt,allclus] = rowMeans(dat[(lmk+1):ldt, cluster == allclus, drop = F]) -->
<!--       }else{ -->
<!--         mu[(lmk+1):ldt,allclus] = rep(0, ldt-lmk) -->
<!--       } -->
<!--     } -->
<!--   } -->

<!--   cost = cost_func(dat, cluster, mu, design_mat) -->
<!--   return(list(mu, cluster, cost)) -->
<!-- } -->
<!-- ``` -->

#scsorter:experiment -->
<!-- ```{r} -->
<!-- #Preprocess Data -->
<!-- ## add drop = FALSE to correct matrix automatic to vector problem -->
<!-- data_preprocess_edited = function(expr, anno_processed) { -->

<!--   designmat = anno_processed[[1]] -->
<!--   weightmat = anno_processed[[2]] -->

<!--   rownames(expr) = toupper(rownames(expr)) -->
<!--   rownames(designmat) = toupper(rownames(designmat)) -->

<!--   markers = rownames(designmat) -->

<!--   markers_avail = markers %in% rownames(expr) -->

<!--   if (sum(markers_avail) < length(markers)) { -->
<!--     warning(paste('The following specified marker genes are not found from the expression data: ', -->
<!--                   paste(markers[!markers_avail], collapse = ', '), '.', sep = '')) -->

<!--     designmat_test <- designmat[markers_avail, ,drop = FALSE] -->
<!--     csdmat = colSums(designmat) -->

<!--     if(sum(csdmat > 0) < ncol(designmat)) { -->
<!--       stop(paste('None of the marker genes specfied for the following cell types could be found from the expression data: ', -->
<!--                  paste(colnames(designmat)[csdmat == 0], collapse = ', '), '. \n Please maker sure the marker gene names are correctly specified.', sep = '')) -->
<!--     } -->
<!--   } -->

<!--   dmat_gene_names = rownames(designmat) -->
<!--   dat_gene_names = rownames(expr) -->

<!--   picker = dat_gene_names %in% dmat_gene_names -->

<!--   expr_mk = expr[picker, , drop = FALSE] -->
<!--   expr_rt = expr[!picker,, drop = FALSE] -->


<!--   #reorder genes so that the order of expr mat and design mat matches -->
<!--   ror = rep(0, nrow(designmat)) -->
<!--   for(i in 1:nrow(designmat)){ -->
<!--     print(i) -->
<!--     ror[i] = which(rownames(expr_mk) == dmat_gene_names[i]) -->
<!--   } -->
<!--   expr_mk = expr_mk[ror,, drop = FALSE] -->

<!--   expr_cb = rbind(expr_mk, expr_rt) -->

<!--   return(list(dat = expr_cb, designmat = designmat, weightmat = weightmat)) -->
<!-- } -->

<!-- scSorter_edited <- function (expr, anno, default_weight = 2, n_start = 10, alpha = 0,  -->
<!--           u = 0.05, max_iter = 100, setseed = 0)  -->
<!-- { -->
<!--   anno_processed = design_matrix_builder(anno, default_weight) -->
<!--   dt = data_preprocess_edited(expr, anno_processed) -->
<!--   dat = dt[[1]] -->
<!--   designmat = dt[[2]] -->
<!--   weightmat = dt[[3]] -->
<!--   c_cost = NULL -->
<!--   c_mu = list() -->
<!--   c_clus = list() -->
<!--   for (i in 1:n_start) { -->
<!--     set.seed(i + setseed) -->
<!--     t1 = Sys.time() -->
<!--     pred_ot = update_func(as.matrix(dat), designmat, weightmat,  -->
<!--                           unknown_threshold1 = alpha, unknown_threshold2 = u,  -->
<!--                           max_iter = max_iter) -->
<!--     t2 = Sys.time() -->
<!--     c_cost = c(c_cost, pred_ot[[3]]) -->
<!--     c_mu[[i]] = pred_ot[[1]] -->
<!--     c_clus[[i]] = pred_ot[[2]] -->
<!--   } -->
<!--   pk = which.min(c_cost) -->
<!--   pred_clus = c_clus[[pk]] -->
<!--   pred_clus = c(colnames(designmat), rep("Unknown", ncol(designmat)))[pred_clus] -->
<!--   pred_mu = c_mu[[pk]] -->
<!--   return(list(Pred_Type = pred_clus, Pred_param = pred_mu)) -->
<!-- } -->

<!-- design_matrix_builder = function(anno, weight){ -->
<!--   if(weight <= 0)stop(paste('Default weight should be positive instead of the assigned value of ', weight, '.', sep = '')) -->

<!--   colnames(anno) = toupper(colnames(anno)) -->

<!--   if(sum(c('TYPE', 'MARKER') %in% colnames(anno)) == 2) { -->
<!--     ror = c(which(colnames(anno) == 'TYPE'), which(colnames(anno) == 'MARKER')) -->
<!--     lidx = c(1:ncol(anno))[!(1:ncol(anno) %in% ror)] -->
<!--     ror = c(ror, lidx) -->
<!--     anno = anno[, ror] -->
<!--   } -->

<!--   celltypes = unique(anno[,1]) -->
<!--   marker = unique(anno[,2]) -->

<!--   nc = length(celltypes) -->
<!--   nm = length(marker) -->

<!--   designmat = matrix(0, nm, nc) -->

<!--   nc_anno = ncol(anno) -->

<!--   if (nc_anno == 3) { -->
<!--     anno[, 3] = as.numeric(anno[, 3]) -->
<!--     poscheck = (anno[, 3] <= 0) -->
<!--     if(sum(poscheck) > 0) { -->
<!--       stop(paste('Please assign positive weights for the following marker genes: \n', -->
<!--                  paste(sapply(1:nrow(anno), function(x)paste(anno[x, 1 ], anno[x, 2], sep = ': '))[poscheck], collapse = ', \n'), -->
<!--                  '.', sep = '')) -->
<!--     } -->
<!--     weight = min(anno[, 3]) -->
<!--   } -->

<!--   weightmat = matrix(weight, nm, nc) -->

<!--   for (i in 1:nrow(anno)) { -->
<!--     designmat[which(marker == anno[i, 2]), which(celltypes == anno[i, 1])] = 1 -->
<!--     if (nc_anno == 3) weightmat[which(marker == anno[i, 2]), which(celltypes == anno[i, 1]),drop = FALSE] = anno[i, 3] -->
<!--   } -->

<!--   designmat = as.data.frame(designmat, stringsAsFactors = F) -->
<!--   colnames(designmat) = celltypes -->
<!--   rownames(designmat) = marker -->

<!--   colnames(weightmat) = celltypes -->
<!--   rownames(weightmat) = marker -->

<!--   return(list(designmat, weightmat)) -->
<!-- } -->
<!-- ``` -->

<!-- ```{r} -->
<!-- rts <- scSorter_edited(expr, anno) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- anno_processed <- design_matrix_builder(anno,2) -->
<!-- class(test[[1]]) -->

<!--   library(venn) -->
<!-- venn::venn(list(exp = rownames(expr_mk),dmat_gene_names)) -->
<!-- length(dmat_gene_names) -->
<!-- rownames(expr_mk) == dmat_gene_names[17] -->
<!-- rownames(expr_mk) == dmat_gene_names[i] -->

<!-- dmat_gene_names[17] -->
<!-- rownames(expr_mk) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- markers -->
<!-- markers_avail -->
<!-- sum(markers_avail) < length(markers) -->
<!-- markers_avail -->
<!-- designmat -->
<!-- ``` -->

#scsorter:continue
```{r}
rts.list <- lapply(gbm.list.res, "[[", 1)


#Keep rts results of all
saveRDS(rts.list,paste0("output/intermediate_process_tool/scsorter_rts_",object,"_",sig), compress = TRUE)
```


```{r}
gbm.list.res <- lapply(gbm.list.res, "[[", 2)
```

```{r}
#Demultiplex list
each.meta.df <- data.frame()

for (i in 1:length(gbm.list.res)) {
  each.meta.df <- rbind(each.meta.df,data.frame(gbm.list.res[[i]]))
}

colnames(each.meta.df)[1] <- "cell_id"
```



```{r}
write.csv(each.meta.df,paste0("output/annotation_result_each_toolys/scsorter_",object,"_",sig,"_",run,".csv"),row.names = TRUE)
```

```{r}
unloadNamespace("scSorter")
rm(anno,gbm.list.res,each.meta.df)
gc()
```





#UCell -->
<!-- ```{r} -->
<!-- library(UCell) -->
<!-- #load subtpye signature -->
<!-- #signatures <- read_xlsx("data/gbm_subtype_genelist.xlsx",sheet = 2) -->
<!-- #signatures <- read_xlsx("data/gbm_subtype_new_original.xlsx",sheet = 2) -->

<!-- #signatures <- read.csv(paste0("output/signature_subtype_",sig,".csv")) -->

<!-- signatures.ucell <- read_xlsx("data/MESImm_original.xlsx",sheet = 3) -->


<!-- signatures.ucell <- as.list(signatures.ucell) -->
<!-- signatures.ucell <- lapply(signatures.ucell, na.omit) -->

<!-- ``` -->


<!-- ```{r} -->
<!-- gbm <- gbm.original -->
<!-- gbm <- NormalizeData(gbm,verbose = FALSE) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- gbm <- AddModuleScore_UCell(gbm, features =signatures) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- gbm.meta <- gbm@meta.data -->
<!-- gbm.meta.colnames <- colnames(gbm.meta) -->
<!-- gbm.meta.colnames -->

<!-- ``` -->


<!-- ```{r} -->
<!-- phenotype <- gbm.meta.colnames[grepl('*_UCell', gbm.meta.colnames)] -->
<!-- score <- gbm@meta.data[,phenotype] -->


<!-- celltype.all <- c() -->
<!-- for (i in 1:nrow(score)) { -->

<!--   score_cell <- sort(unlist((score[i,])),decreasing = TRUE) -->
<!--   celltype <- names(score_cell[1]) -->
<!--   celltype.all <- append(celltype.all,celltype) -->

<!-- } -->

<!-- ``` -->
<!-- ```{r} -->
<!-- max(score) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- gbm$UCell <- celltype.all -->

<!-- each.meta.df <- gbm@meta.data[c("UCell")] -->

<!-- ``` -->

<!-- ```{r} -->
<!-- each.meta.df -->
<!-- table(each.meta.df$UCell) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- write.csv(each.meta.df,paste0("output/UCell_",object,"_",sig,".csv"),row.names = TRUE) -->
<!-- ``` -->

#scID:marker-based -->
<!-- ```{r} -->
<!-- library(readxl) -->
<!-- # markers <- read_xlsx("data/gbm_subtype_new_scID.xlsx") -->
<!-- # markers$cluster <- as.factor(markers$cluster) -->

<!-- markers <- signatures.scid -->
<!-- markers$cluster <- as.factor(markers$cluster) -->

<!-- rownames(markers) <- markers$gene -->
<!-- markers.head <- head(markers,20) -->

<!-- markers.test <-readRDS("data/example/scID/markers.rds") -->
<!-- ``` -->


<!-- ```{r} -->
<!-- # Ref -->
<!-- # neftel.smt <- readRDS("output/smrt_mal") -->
<!-- # reference_gem <- as.matrix(neftel.smt@assays$norm@data) -->
<!-- # reference_clusters <- neftel.smt$celltype_merge -->
<!-- #  -->
<!-- # neftel.cell.id <- names(reference_clusters) -->
<!-- # reference_clusters <- as.factor(gsub("like",".new",reference_clusters)) -->
<!-- #  -->
<!-- # names(reference_clusters) <- neftel.cell.id -->


<!-- # Target -->
<!-- gbm <- readRDS("output/seurat_gbm_qc") -->
<!-- gbm.list <- SplitObject(gbm, split.by = "split") -->
<!-- gbm.list[["run2_radiated_E31N"]] <- merge(gbm.list[["run2_radiated_E31N"]], y=gbm.list[["run1_radiated_E31N"]]) -->
<!-- gbm.list[["run2_control_E31N"]] <- merge(gbm.list[["run2_control_E31N"]], y=gbm.list[["run1_control_E31N"]]) -->
<!-- gbm.list[["run2_radiated_E26N"]] <- merge(gbm.list[["run2_radiated_E26N"]], y=gbm.list[["run1_radiated_E26N"]]) -->
<!-- gbm.list[["run2_radiated_E24N"]] <- merge(gbm.list[["run2_radiated_E24N"]], y=gbm.list[["run1_radiated_E24N"]]) -->
<!-- gbm.list[c("run1_radiated_E24N","run1_radiated_E26N","run1_control_E31N","run1_radiated_E31N")] <- NULL -->
<!-- ``` -->


<!-- ```{r} -->
<!-- rm(gbm,neftel.smt) -->
<!-- gc() -->
<!-- ``` -->


<!-- ```{r message=FALSE, warning=FALSE, paged.print=FALSE} -->
<!-- x <- NormalizeData(gbm.list$run1_control_E55N,normalization.method = "RC",verbose = FALSE) -->
<!-- time1 <- system.time(test <- rowSums(as.matrix(x@assays$RNA@counts) != 0)) -->
<!-- time1  -->


<!-- x@assays$RNA@counts[1:3,1:3] -->
<!-- str(x@assays$RNA@counts) -->
<!-- str(as.matrix(x@assays$RNA@counts)[1,1]) -->
<!-- str(gbm.list$run1_control_E55N@assays) -->
<!-- gbm.list[4:5] -->
<!-- ``` -->


<!-- ```{r} -->
<!-- n.cores <- 1 -->
<!-- #n.cores <- parallel::detectCores() - 2 -->
<!-- system.time(gbm.list.res <- lapply(X = gbm.list[4:5], FUN = function(x)  { -->
<!-- #system.time(gbm.list.res <- mclapply(X = gbm.list, mc.cores = n.cores, FUN = function(x)  { -->
<!--   x <- NormalizeData(x,normalization.method = "RC",verbose = FALSE) -->
<!--   x <- as.matrix(x@assays$RNA@data) -->
<!--   # If want to set estimate_weights_from_target = TRUE, need older version of biomod2 (3.5.1) -->
<!--   scID_output <- scid_multiclass(target_gem = x, markers = markers.head, estimate_weights_from_target = TRUE,logFC = 0.6, only_pos = TRUE) -->
<!--   return(scID_output) -->
<!--   gc() -->
<!-- })) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- saveRDS(gbm.list.res, file = paste0("output/scID_markers",object,"_",sig)) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- print(1) -->
<!-- ``` -->


<!-- ```{r} -->
<!-- res.df <- data.frame() -->
<!-- for (i in gbm.list.res) { -->
<!--   res.each.df <- cbind(data.frame(i$labels, stringsAsFactors = TRUE),data.frame(t(i$scores))) -->
<!--   res.df <- rbind(res.df,res.each.df) -->
<!-- } -->
<!-- colnames(res.df)[1] <- "scID_unassigned" -->
<!-- ``` -->
<!-- ```{r} -->
<!-- score <- res.df[grepl('*new', colnames(res.df))] -->
<!-- score -->

<!-- celltype.all <- c() -->
<!-- for (i in 1:nrow(score)) { -->
<!--   score_cell <- sort(unlist((score[i,])),decreasing = TRUE) -->

<!--   celltype <- names(score_cell[1]) -->
<!--   celltype.all <- append(celltype.all,celltype) -->

<!-- } -->
<!-- res.df$scID <- celltype.all -->
<!-- ``` -->


<!-- ```{r} -->
<!-- library(tibble) -->
<!-- res.df <- rownames_to_column(res.df) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- head(res.df) -->
<!-- table(res.df$scID) -->
<!-- table(res.df$scID_unassigned) -->
<!-- head(res.df, 30) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- write.csv(res.df,paste0("output/scID_markers_",object,"_",sig,".csv"),row.names = FALSE) -->
<!-- ``` -->






#MarkerCount (the analysis part is in python code)

```{r}
# gbm <- gbm.original
# 
# SaveH5Seurat(gbm, filename = paste0("output/gbm_qc.h5Seurat"), overwrite = TRUE)
# 
# Convert(paste0("output/gbm_qc.h5Seurat"), dest = "h5ad",overwrite = TRUE)
```

#clustifyr_marker -->
<!-- ```{r} -->
<!-- library(clustifyr) -->
<!-- library(Seurat) -->
<!-- ``` -->



<!-- ```{r} -->
<!-- gbm <- readRDS("output/seurat_gbm_qc") -->
<!-- gbm.list <- SplitObject(gbm, split.by = "split") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- gbm.list[["run2_radiated_E31N"]] <- merge(gbm.list[["run2_radiated_E31N"]], y=gbm.list[["run1_radiated_E31N"]]) -->
<!-- gbm.list[["run2_control_E31N"]] <- merge(gbm.list[["run2_control_E31N"]], y=gbm.list[["run1_control_E31N"]]) -->
<!-- gbm.list[["run2_radiated_E26N"]] <- merge(gbm.list[["run2_radiated_E26N"]], y=gbm.list[["run1_radiated_E26N"]]) -->
<!-- gbm.list[["run2_radiated_E24N"]] <- merge(gbm.list[["run2_radiated_E24N"]], y=gbm.list[["run1_radiated_E24N"]]) -->
<!-- gbm.list[c("run1_radiated_E24N","run1_radiated_E26N","run1_control_E31N","run1_radiated_E31N")] <- NULL -->
<!-- ``` -->



<!-- ```{r} -->
<!-- #try using marker based -->
<!-- library(readxl) -->
<!-- #signatures <- read_xlsx("data/gbm_subtype_new_original.xlsx",sheet = 2) -->

<!-- signatures <- read.csv(paste0("output/signature_subtype_",merge,".csv")) -->


<!-- system.time(gbm.list.res <- mclapply(X = gbm.list, mc.cores = n.cores, FUN = function(x)  { -->
<!--   x <- NormalizeData(x,verbose = FALSE) -->
<!--   allgenes <- rownames(x) -->
<!--   x <- FindVariableFeatures(x,verbose = FALSE) -->
<!--   x <- ScaleData(x, features = allgenes ,verbose = FALSE) -->
<!--   x <- RunPCA(x, verbose = FALSE) -->
<!--   x <- FindNeighbors(x, reduction = "pca", dims = 1:20, verbose = FALSE) -->
<!--   x <- FindClusters(x, resolution = 1, verbose = FALSE) -->

<!--   print(paste("Analizing",names(gbm.list)[i])) -->
<!--   res <- clustify_lists( -->
<!--     input = x,              -->
<!--     cluster_col = "RNA_snn_res.1", -->
<!--     marker = signatures,                 -->
<!--     metric = "pct",  -->
<!--     threshold = 0, -->
<!--     verbose = FALSE) -->
<!--   return(res@meta.data[c("type","r")]) -->
<!-- }))   -->
<!-- ``` -->

<!-- ```{r} -->
<!-- names(gbm.list.res) <- NULL -->
<!-- res.marker.df <- NULL -->
<!-- res.marker.df <- do.call(rbind,gbm.list.res) -->
<!-- colnames(res.marker.df) <- c("clustifyr_marker","r_marker") -->
<!-- ``` -->

<!-- ```{r} -->
<!-- all <- data.frame() -->
<!-- all <- cbind(res.ref.df,res.marker.df) -->
<!-- ``` -->

<!-- ```{r} -->
<!-- write.csv(all,paste0("output/clustifyr_marker_",object,"_",merge,".csv"),row.names = TRUE) -->
<!-- ``` -->

