```{r}
library(here)
library(tibble)
library(dplyr)
```

```{r}
#Set working directory
setwd(here())
```
```{r}
# Parameter
# cell input to be analyse

object <- "all"

sigs <- c( "4metamodules_new_50_mes","6metamodules", "3metamodules_new_50", "4metamodules_new_50")



# For reference based
merges <- c("6metamodules", "4_merge_metamodules", "4_merge_metamodules_3celltypes", "4_merge_metamodules_mes")


unknowns <- c("","_no_unknown")
# pick which celltype to be analyse

# all_celltypes <- c("AClike", "MESlike", "NPClike", "OPClike")
# chosen_celltypes <- all_celltypes[c(2)]

run_eachs <- c(TRUE,FALSE)
runs <- c("","whole")

```
```{r}

pick <- 3
sig <- sigs[pick]
merge <- merges[pick]


run_each <- run_eachs[2]
if (run_each) {
  run <- runs[1]
} else {
  run <- runs[2]
}

```
```{r}
#set unknown 
unknown <- unknowns[1]
```


```{r}
# import all data
# marker.based
sc.type <- read.csv(paste0("output/scType_", object, "_", sig, ".csv"), row.names = 1)
sc.type <- sc.type[,paste0("scType",unknown) ,drop = FALSE]

scina <- read.csv(paste0("output/SCINA_", object, "_", sig, ".csv"), row.names = 1)
scina <- scina[,paste0("SCINA",unknown) ,drop = FALSE]
```


```{r}
unknown <- unknowns[1]
# ref-based
clustify.r <- read.csv(paste0("output/clustifyr_", object, "_", merge, ".csv"), row.names = 1)
#clustify.r <- clustify.r[,paste0("clustifyr_ref",unknown) ,drop = FALSE]
clustify.r <- clustify.r[,paste0("clustifyr_ref") ,drop = FALSE]

scid <- read.csv(paste0("output/scID_", object, "_", merge,"_allassigned",".csv"), row.names = 1)
scid <- scid[,paste0("scID",unknown) ,drop = FALSE]
```


```{r}
anno_3subtype <- bind_cols(sc.type, scina, clustify.r,scid)

#colnames(anno_3subtype) <- paste(colnames(anno_3subtype), sig, sep = "_")

anno_3subtype[] <- lapply(anno_3subtype, function(x) gsub("\\.new$", "like", x))
anno_3subtype[] <- lapply(anno_3subtype, function(x) gsub("Unknown", "unknown", x))
anno_3subtype[] <- lapply(anno_3subtype, function(x) gsub("unassigned", "unknown", x))
```






```{r}
# Do sankey
library(ggsankey)
library(ggplot2)


all.sankey <- anno_3subtype

df <- all.sankey %>%
  make_long(colnames(all.sankey))

# Chart 1
pl <- ggplot(df, aes(
  x = x,
  next_x = next_x,
  node = node,
  next_node = next_node,
  fill = factor(node),
  label = node
))
pl <- pl + geom_sankey(
  flow.alpha = 0.5,
  node.color = "black",
  show.legend = FALSE
)
pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
pl <- pl + theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl + theme(
  axis.title = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank()
)

# pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = paste(object, sig, sep = "; "))
pl <- pl + labs(fill = "Nodes")
pl
```
```{r}


# MES
sig <- sigs[4]
merge <- merges[4]
# import all data
# marker.based
sc.type <- read.csv(paste0("output/scType_", object, "_", sig, ".csv"), row.names = 1)
sc.type <- sc.type[,paste0("scType") ,drop = FALSE]
sc.type[] <- lapply(sc.type, function(x) gsub("Unknown", "Non_MESlike", x))


scina <- read.csv(paste0("output/SCINA_", object, "_", sig, ".csv"), row.names = 1)
scina <- scina[,paste0("SCINA") ,drop = FALSE]
scina[] <- lapply(scina, function(x) gsub("unknown", "Non_MESlike", x))

# ref-based
clustify.r <- read.csv(paste0("output/clustifyr_", object, "_", merge, ".csv"), row.names = 1)
#clustify.r <- clustify.r[,paste0("clustifyr_ref",unknown) ,drop = FALSE]
clustify.r <- clustify.r[,paste0("clustifyr_ref") ,drop = FALSE]
clustify.r[] <- lapply(clustify.r, function(x) gsub("not_labeled", "Non_MESlike", x))

scid <- read.csv(paste0("output/scID_", object, "_", merge,"_allassigned",".csv"), row.names = 1)
scid <- scid[,paste0("scID",unknown) ,drop = FALSE]
#scid <- scid[,paste0("scID",unknowns[2]) ,drop = FALSE]

scid[] <- lapply(scid, function(x) gsub("not_labeled", "Non_MESlike", x))

#scid[] <- lapply(scid, function(x) gsub("unassigned", "unknown", x))
scid[] <- lapply(scid, function(x) gsub("unassigned", "Non_MESlike", x))

anno_mes <- bind_cols(sc.type, scina, clustify.r,scid)

anno_mes[] <- lapply(anno_mes, function(x) gsub("\\.new$", "like", x))
anno_mes
```





```{r}
# Do sankey
library(ggsankey)
library(ggplot2)


all.sankey <- anno_mes

df <- all.sankey %>%
  make_long(colnames(all.sankey))

# Chart 1
pl <- ggplot(df, aes(
  x = x,
  next_x = next_x,
  node = node,
  next_node = next_node,
  fill = factor(node),
  label = node
))
pl <- pl + geom_sankey(
  flow.alpha = 0.5,
  node.color = "black",
  show.legend = FALSE
)
pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
pl <- pl + theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl + theme(
  axis.title = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank()
)

# pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = paste(object, sig, sep = "; "))
pl <- pl + labs(fill = "Nodes")
pl
```



```{r}
# Merge information
anno_3subtype <- anno_3subtype[order(rownames(anno_3subtype)), ]
anno_mes <- anno_mes[order(rownames(anno_mes)), ]

annon_mes_edited <- anno_mes %>% mutate(across(everything(), ~na_if(., "Non_MESlike")))
anno_merge <- mapply(paste, anno_3subtype, annon_mes_edited, MoreArgs = list(sep = "_"))


anno_merge <- as.data.frame(anno_merge)
rownames(anno_merge) <- rownames(anno_mes)

anno_merge[] <- lapply(anno_merge, function(x) gsub("_NA", "", x))


```
```{r}
# Do sankey
library(ggsankey)
library(ggplot2)



all.sankey <- anno_merge

df <- all.sankey %>%
  make_long(colnames(all.sankey))
df

# Chart 1
pl <- ggplot(df, aes(
  x = x,
  next_x = next_x,
  node = node,
  next_node = next_node,
  fill = factor(node),
  label = node
))
pl <- pl + geom_sankey(
  flow.alpha = 0.5,
  node.color = "black",
  show.legend = FALSE
)
pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
pl <- pl + theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl + theme(
  axis.title = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank()
)

# pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = paste(object, sig, sep = "; "))
pl <- pl + labs(fill = "Nodes")
pl
```

```{r}
#add gbm metadata
gbm.meta <- read.csv("output/gbm_meta.csv",row.names = 1)
gbm.meta
anno_merge_radiation <- cbind(anno_merge,gbm.meta[,"radiation"])

anno_merge_radiation
```

```{r}
# Sankey on control
# Do sankey
library(ggsankey)
library(ggplot2)



all.sankey <- anno_merge_radiation[anno_merge_radiation$`gbm.meta[, "radiation"]` == "control",1:4]

df <- all.sankey %>%
  make_long(colnames(all.sankey))
df

# Chart 1
pl <- ggplot(df, aes(
  x = x,
  next_x = next_x,
  node = node,
  next_node = next_node,
  fill = factor(node),
  label = node
))
pl <- pl + geom_sankey(
  flow.alpha = 0.5,
  node.color = "black",
  show.legend = FALSE
)
pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
pl <- pl + theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl + theme(
  axis.title = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank()
)

# pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = paste(object, sig, sep = "; "),
                subtitle = "control")
pl <- pl + labs(fill = "Nodes")
pl
```
```{r}
# Sankey on control
# Do sankey
library(ggsankey)
library(ggplot2)



all.sankey <- anno_merge_radiation[anno_merge_radiation$`gbm.meta[, "radiation"]` == "radiated",1:4]

df <- all.sankey %>%
  make_long(colnames(all.sankey))
df

# Chart 1
pl <- ggplot(df, aes(
  x = x,
  next_x = next_x,
  node = node,
  next_node = next_node,
  fill = factor(node),
  label = node
))
pl <- pl + geom_sankey(
  flow.alpha = 0.5,
  node.color = "black",
  show.legend = FALSE
)
pl <- pl + geom_sankey_label(size = 2, color = "black", fill = "white")
pl <- pl + theme_bw()
pl <- pl + theme(legend.position = "none")
pl <- pl + theme(
  axis.title = element_blank(),
  axis.text.y = element_blank(),
  axis.ticks = element_blank(),
  panel.grid = element_blank()
)

# pl <- pl + scale_fill_viridis_d(option = "inferno")
pl <- pl + labs(title = paste(object, sig, sep = "; "),
                subtitle = "radiated")
pl <- pl + labs(fill = "Nodes")
pl
```
```{r}
# convert the 4 tools into 4 dimention of subtype 
library(data.table)

# First defined MES score range from 0 to 1
anno_mes_score <- as.data.table(anno_mes,keep.rownames = TRUE)

# Replace MESlike and Non-MESLike with 1 and 0
anno_mes_score[, (2:5) := lapply(.SD, function(x) fifelse(x == "MESlike", 1, fifelse(x == "Non-MESLike", 0, NA_integer_))), .SDcols = 2:5]

# Rowwise summation of columns 2 to 5

anno_mes_score[, sum_col := rowSums(.SD, na.rm = TRUE)/ncol(anno_mes), .SDcols = 2:5]

# Creating a new data table with the first column and the summation
anno_mes_score <- anno_mes_score[, .(rn = rn, MESlike = sum_col)]


```
```{r}
anno_3subtype[rownames(anno_3subtype) == "run1_control_TACCGGGTCTAAGAAG-1",]
```

```{r}
anno_3subtype_wide <- as.data.table(anno_3subtype,keep.rownames = TRUE)
anno_3subtype_wide[, (colnames(anno_3subtype_wide)) := lapply(.SD, function(x) fifelse(x == "unknown", NA_character_, x))]

anno_3subtype_score_long <- melt(anno_3subtype_wide, id.vars = "rn", variable.name = "tools", value.name = "cell_types")

anno_3subtype_score_long <- anno_3subtype_score_long[,c(1,3)]
anno_3subtype_score_long[,binary := 1]
anno_3subtype_score <- dcast(anno_3subtype_score_long,formula = rn ~cell_types ,value.var = "binary")

anno_3subtype_score <- anno_3subtype_score[,-c("NA")]
anno_3subtype_score[, 2:4 := .SD/ncol(anno_3subtype), .SDcols = 2:4]
anno_3subtype_score

```



```{r}
anno_4subtype_score <- merge(anno_3subtype_score,anno_mes_score,by = "rn")
anno_4subtype_score
```
# ```{r}
# library(uwot)
# set.seed(123)
# 
# umap_res <- umap(anno_4subtype_score[,2:5],n_threads = parallel::detectCores())
# 
# umap_res <- as.data.frame(umap_res,row.names = anno_4subtype_score$rn)
# colnames(umap_res) <- c("UMAP_1","UMAP_2")
# 
# library(Rtsne)
# set.seed(123)
# tsne_res <- Rtsne(anno_4subtype_score[,2:5], dims = 2, perplexity = 30, theta = 0.5, check_duplicates = FALSE)
# tsne_res <- as.data.frame(tsne_res$Y,row.names = anno_4subtype_score$rn)
# colnames(tsne_res) <- c("tSNE_1","tSNE_2")
# 
# #MDS
# set.seed(123)
# dist_mat <- dist(anno_4subtype_score[,2:5])  # Euclidean distance is the default
# mds_res <- cmdscale(dist_mat, k = 2)
# mds_res <- as.data.frame(mds_res,row.names = anno_4subtype_score$rn)
# colnames(mds_res) <- c("MDS_1","MDS_2")
# ```
# 
# ```{r}
# tsne_res
# map_list <- list(umap_res,tsne_res)
# reduced_map <- do.call(cbind,map_list)
# 
# reduced_map <- cbind(reduced_map,gbm.meta)
# reduced_map
# ```
# ```{r}
# library(bigmemory)
# library(biganalytics)
# install.packages("biganalytics")
# anno_4subtype_score_big <- as.big.matrix(anno_4subtype_score[,2:5])
# anno_4subtype_score_big
# ```
# 
# ```{r}
# library(cluster)
# 
# # Perform K-means clustering
# set.seed(42)
# kmeans_result <- bigkmeans(anno_4subtype_score_big,centers = 3)
# 
# # Calculate silhouette scores
# silhouette_scores <- silhouette(kmeans_result$cluster, dist(anno_4subtype_score[,2:5]))
# 
# # Plot silhouette scores
# plot(silhouette_scores)
# 
# 
# wcss <- sapply(1:10, function(k) {
#   sum(bigkmeans(anno_4subtype_score_big,centers = k)$withinss)
# })
# wcss
# # Plot the elbow method
# plot(1:10, wcss, type = "b", xlab = "Number of Clusters", ylab = "WCSS")
# ```
# 
# ```{r}
# ggplot(reduced_map, aes(x = UMAP_1, y = UMAP_2)) +
#   geom_point(size = 0.1)
# ```
# 
# ```{r}
# ggplot(reduced_map, aes(x = tSNE_1, y = tSNE_2,color = radiation)) +
#   geom_point(size = 0.1)
# ```
```{r}


library(data.table)
library(scatterplot3d)

# Assuming 'anno_4subtype_score' and 'gbm.meta' are data.tables
score_4subtype_meta <- cbind(anno_4subtype_score, gbm.meta)
score_4subtype_meta[, radiation := as.factor(radiation)]
score_4subtype_meta[, c("AClike", "NPClike", "OPClike") := lapply(.SD, as.numeric), .SDcols = c("AClike", "NPClike", "OPClike")]
score_4subtype_meta[, rank := frank(score_4subtype_meta$MESlike, ties.method = "dense")]

# Calculate the frequency of each unique combination of AClike, NPClike, and OPClike
freq_table <- score_4subtype_meta[, .N, by = .(AClike, NPClike, OPClike)]
score_4subtype_meta <- merge(score_4subtype_meta, freq_table, by = c("AClike", "NPClike", "OPClike"))

# Color by MES
colors <- colorRampPalette(c("blue", "white"))(ncol(anno_merge)+1)
colors <- colors[as.numeric(score_4subtype_meta$rank)]

# Shape by radiation
shapes <- c(16, 17)
shapes <- shapes[as.numeric(score_4subtype_meta$radiation)]



# Create 3D scatter plot
scatterplot3d(score_4subtype_meta$AClike, score_4subtype_meta$NPClike, score_4subtype_meta$OPClike,
              color = colors,
              pch = shapes,
              grid = TRUE, box = FALSE,
              xlab = "AClike", ylab = "NPClike", zlab = "OPClike",
              type = "h")

text(x = 7, y = 0.5, "NPClike", srt = 25)

legend("top", legend = levels(score_4subtype_meta$radiation),
       pch = shapes,
       inset = -0.25, xpd = TRUE, horiz = TRUE)
```
```{r}
# Better plot into python as i can manage to adjust the size

library(feather)
score_4subtype_meta
# Save the data.table as a feather file
write_feather(score_4subtype_meta, "output/score_4subtype_meta.feather")
```


```{r}
#try rgl
# 
# library(rgl)
# 
# score_4subtype_meta <- cbind(anno_4subtype_score, gbm.meta)
# score_4subtype_meta[, radiation := as.factor(radiation)]
# score_4subtype_meta[, c("AClike", "NPClike", "OPClike") := lapply(.SD, as.numeric), .SDcols = c("AClike", "NPClike", "OPClike")]
# score_4subtype_meta[, rank := frank(score_4subtype_meta$MESlike, ties.method = "dense")]
# 
# # Calculate the frequency of each unique combination of AClike, NPClike, and OPClike
# freq_table <- score_4subtype_meta[, .N, by = .(AClike, NPClike, OPClike)]
# score_4subtype_meta <- merge(score_4subtype_meta, freq_table, by = c("AClike", "NPClike", "OPClike"))
# 
# # Color by MES
# colors <- colorRampPalette(c("blue", "white"))(ncol(anno_merge)+1)
# colors <- colors[as.numeric(score_4subtype_meta$rank)]
# 
# # Shape by radiation
# shapes <- c(16, 17)
# shapes <- shapes[as.numeric(score_4subtype_meta$radiation)]
# 
# 
# # Normalize the 'N' column for point sizes
# max_size <- 10  # Maximum size for a point
# min_size <- 3   # Minimum size for a point
# 
# # Add a new column for the scaled size
# score_4subtype_meta[, size_factor := ((N - min(N)) / (max(N) - min(N))) * (max_size - min_size) + min_size]
# 
# 
# # Open a new 3D plotting device
# rgl.open()
# 
# # Plot the points
# with(score_4subtype_meta, plot3d(x = AClike, y = NPClike, z = OPClike,
#                                 col = colors, pch = shapes, size = size_factor,
#                                 xlab = "AClike", ylab = "NPClike", zlab = "OPClike"))
# # Add axes
# axes3d(edges = c("x--", "y--", "z--"))
# 
# # Add legend (Note: rgl does not have a built-in legend function, so this is a workaround)
# legend3d("top", legend = levels(score_4subtype_meta$radiation), pch = shapes, col = colors)
# 
# # Optionally, add a title
# title3d("3D Scatter Plot")
# 
# # To interact with the plot, you can use the mouse to rotate, zoom, and pan.

```




```{r}
anno_3subtype_score_per <- anno_3subtype_score
anno_3subtype_score_per[,2:4] <- anno_3subtype_score[,2:4]

# source("script/function.R")
# anno_3subtype_score_per <- as.data.table(t(apply(anno_3subtype_score_per[,2:4], 1, function(x) adjust_composition_center(x, 0.1))))

score_meta_4subtypes <- Reduce(function(x, y) merge(x, y, by = "rn"), 
                    list(anno_3subtype_score_per, anno_mes_score, rownames_to_column(gbm.meta,var = "rn")))

score_meta_4subtypes[, count := .N, by = .(AClike, NPClike, OPClike)]
```


```{r}
library(extraDistr)
library(tibble)
set.seed(123)  # For reproducibility

# Define the offset size
offset_range = 0
scaling_size = 100

# Calculate a random offset for each group
offsets <- score_meta_4subtypes[, .(offset1 = rdunif(1, -offset_range, offset_range)/scaling_size,
                  offset2 = rdunif(1, -offset_range, offset_range)/scaling_size,
                  offset3 = rdunif(1, -offset_range, offset_range)/scaling_size), by = radiation]
#offsets[2,2:4] <- 0
offsets
# Join the offsets back to the original data
score_meta_4subtypes <- merge(score_meta_4subtypes, offsets, by = "radiation")

#First, adjust the values with the offsets
score_meta_4subtypes[, `:=` (AClike = AClike + offset1,
                             NPClike = NPClike + offset2,
                             OPClike = OPClike + offset3)]



# Then, calculate the total
score_meta_4subtypes[, total := AClike + NPClike+ OPClike]

# Finally, normalize the adjusted values
score_meta_4subtypes[, `:=` (AClike = round(AClike / total,digits = 3)*100,
                             NPClike = round(NPClike / total,digits = 3)*100,
                             OPClike = round(OPClike / total,digits = 3)*100)]


```

```{r}
library(ggtern)
plot <- ggtern(data = score_meta_4subtypes, aes(x = AClike, y = NPClike, z = OPClike)) +
  geom_mask() +
  geom_point(aes(shape = radiation, size = count, color = MESlike)) +
  scale_color_gradient(low = "grey", high = "purple") +
  scale_size_continuous(range = c(0.5, 5)) +
  labs(title = "Ternary Plot of Cell Types", size = "Count") +
  facet_wrap(~radiation) +
  # theme(legend.position = "right",
  #       tern.plot.background = element_rect(fill = "white"),
  #       tern.panel.background = element_rect(fill = "grey")) + 
  theme_showgrid()
  

# Display the plot
print(plot)

```

```{r}
length(table(score_meta_4subtypes$count))
score_meta_4subtypes[(score_meta_4subtypes$NPClike >= 1),.(AClike_a,OPClike_a,NPClike_a),by = radiation]
```

```{r}
score_meta_4subtypes[, .SD[sample(.N, 1)], by = .(count)][NPClike==0,]
```

